# Análise de dados TCP-CII

### Importação dos parâmetros universais

In [ ]:
from pathlib import Path
import importlib.util

path = Path("../../../parametros/config.py").resolve()

spec = importlib.util.spec_from_file_location("parametros", path)
parametros = importlib.util.module_from_spec(spec)
spec.loader.exec_module(parametros)

In [ ]:
# Parâmetros importados do arquivo config.py
print("Filtrar por quantidade de alelos TCC1:.........................", parametros.filtarar_por_qte_de_alelos_tcc1)
print("Parâmetro de filtragem median binding percentile TCC1:.........", parametros.parametro_de_filtragem_mbp_tcc1)
print("Percentual de match mínimo TCC1:...............................", parametros.percent_match_minimo_tcc1)

Filtrar por quantidade de alelos TCC1:......................... 10
Parâmetro de filtragem median binding percentile TCC1:......... 5
Percentual de match mínimo TCC1:............................... 95.0

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./T CELL/DENV 3 - T Cell Prediction - Class I.csv')
df

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VSGKLIHEW,303,311,9,HLA-B*57:01,303,0.01,VSGKLIHEW,VSGKLIHEW,0.997373,0.01
1,1,VSGKLIHEW,303,311,9,HLA-B*58:01,303,0.01,VSGKLIHEW,VSGKLIHEW,0.996354,0.01
2,1,TTRMENLLW,60,68,9,HLA-B*57:01,60,0.01,TTRMENLLW,TTRMENLLW,0.990271,0.01
3,1,CTWPKSHTLW,223,232,10,HLA-B*57:01,567,0.01,CTWPKSHTW,CTWPKSHTLW,0.989558,0.01
4,1,EVHTWTEQY,24,32,9,HLA-A*26:01,24,0.01,EVHTWTEQY,EVHTWTEQY,0.988494,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
36985,1,PISEKEENMVKS,337,348,12,HLA-A*24:02,1366,100.00,PISEKMVKS,PISEKEENMVKS,0.000000,100.00
36986,1,PISEKEENMVKS,337,348,12,HLA-A*32:01,1366,100.00,PISENMVKS,PISEKEENMVKS,0.000000,100.00
36987,1,PISEKEENMVKS,337,348,12,HLA-B*35:01,1366,100.00,SEKEENVKS,SEKEENMVKS,0.000000,100.00
36988,1,PISEKEENMVKS,337,348,12,HLA-B*53:01,1366,100.00,PISEKEVKS,PISEKEENMVKS,0.000000,100.00
36989,1,EKEENMVKSLVS,340,351,12,HLA-A*32:01,1369,100.00,ENMVKSLVS,EKEENMVKSLVS,0.000000,100.00

## Selecionando Epítopos por median binding percentile.

In [ ]:
df_mbp_m5 = df[df['median binding percentile'] < parametros.parametro_de_filtragem_mbp_tcc1].copy()
print("Filtrando por median binding percentile < ", parametros.parametro_de_filtragem_mbp_tcc1)
df_mbp_m5

Filtrando por median binding percentile <  5

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTRLENLMW,60,68,9,HLA-B*57:01,60,0.01,VTRLENLMW,VTRLENLMW,0.993804,0.01
1,1,ASGKLITEW,303,311,9,HLA-B*57:01,303,0.01,ASGKLITEW,ASGKLITEW,0.990493,0.01
2,1,ASGKLITEW,303,311,9,HLA-B*58:01,303,0.01,ASGKLITEW,ASGKLITEW,0.989009,0.01
3,1,ETAECPNTNR,139,148,10,HLA-A*68:01,483,0.01,ETAEPNTNR,ETAECPNTNR,0.981131,0.01
4,1,QPTELKYSW,107,115,9,HLA-B*53:01,107,0.01,QPTELKYSW,QPTELKYSW,0.980907,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2519,1,FIEVKNCHW,217,225,9,HLA-A*24:02,217,4.90,FIEVKNCHW,FIEVKNCHW,0.003306,4.90
2520,1,ESEMIIPKNLA,238,248,11,HLA-B*44:02,925,4.90,EEMIIPKNL,ESEMIIPKNL,0.002875,4.90
2521,1,MEIRPLKEKE,333,342,10,HLA-B*44:02,677,4.90,MEIRPLKKE,MEIRPLKEKE,0.002854,4.90
2522,1,FIEVKNCHW,217,225,9,HLA-B*44:02,217,4.90,FIEVKNCHW,FIEVKNCHW,0.002809,4.90
2523,1,TQITGPWHLGKL,262,273,12,HLA-B*40:01,1291,4.90,TQITGPWHL,TQITGPWHLGKL,0.002679,4.90

In [3]:
parametro_de_filtragem_mbp = 5

In [4]:
df_mbp_m5 = df[df['median binding percentile'] < parametro_de_filtragem_mbp].copy()
df_mbp_m5

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VSGKLIHEW,303,311,9,HLA-B*57:01,303,0.01,VSGKLIHEW,VSGKLIHEW,0.997373,0.01
1,1,VSGKLIHEW,303,311,9,HLA-B*58:01,303,0.01,VSGKLIHEW,VSGKLIHEW,0.996354,0.01
2,1,TTRMENLLW,60,68,9,HLA-B*57:01,60,0.01,TTRMENLLW,TTRMENLLW,0.990271,0.01
3,1,CTWPKSHTLW,223,232,10,HLA-B*57:01,567,0.01,CTWPKSHTW,CTWPKSHTLW,0.989558,0.01
4,1,EVHTWTEQY,24,32,9,HLA-A*26:01,24,0.01,EVHTWTEQY,EVHTWTEQY,0.988494,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2604,1,QPMELKYSW,107,115,9,HLA-B*40:01,107,4.90,QPMELKYSW,QPMELKYSW,0.002655,4.90
2605,1,MELKYSWKTW,109,118,10,HLA-B*40:01,453,4.90,MELKYSKTW,MELKYSWKTW,0.002635,4.90
2606,1,SWKLEKASLIEV,209,220,12,HLA-B*40:01,1238,4.90,SEKASLIEV,SWKLEKASLIEV,0.002630,4.90
2607,1,TESCGTRGP,288,296,9,HLA-B*40:01,288,4.90,TESCGTRGP,TESCGTRGP,0.002597,4.90
2608,1,GMEIRPISEK,332,341,10,HLA-B*40:01,676,4.90,GEIRPISEK,GMEIRPISEK,0.002574,4.90

## Agrupando por pepitideos e agregando colunas pertinentes

In [5]:
epitopos_repetidos = (
    df_mbp_m5
    .groupby('peptide', as_index=False)
    .agg(
        start=("start", "first"),
        end=("end", "first"),
        qte_de_alelos=("allele", "nunique"),
        median_binding_percentile=(
            "median binding percentile",
            "median"
        ),
        alelos=(
            "allele",
            lambda x: ", ".join(sorted(x.unique()))
        )
    )
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,AAVKDERAV,186,194,2,3.10,"HLA-A*02:06, HLA-B*51:01"
1,AAVKDERAVH,186,195,2,4.00,"HLA-A*30:02, HLA-B*15:01"
2,ADMGYWIESQK,196,206,2,3.15,"HLA-A*03:01, HLA-A*11:01"
3,ADSPKRLATAI,36,46,1,0.52,HLA-B*07:02
4,AETQNSSFI,126,134,3,0.25,"HLA-B*40:01, HLA-B*44:02, HLA-B*44:03"
...,...,...,...,...,...,...
599,YTQLCDHRL,175,183,9,3.70,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
600,YTQLCDHRLM,175,184,3,3.40,"HLA-A*01:01, HLA-B*57:01, HLA-B*58:01"
601,YTQLCDHRLMSA,175,186,1,2.50,HLA-A*01:01
602,YWIESQKNGSW,200,210,9,1.40,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*4..."
603,YWIESQKNGSWK,200,211,1,4.90,HLA-B*44:02

## Filtragem por qte_de_alelos

In [6]:
filtarar_por_qte_de_alelos = 10

In [7]:
# Filtro do número de alelos
epitopos_repetidos = epitopos_repetidos[
    epitopos_repetidos["qte_de_alelos"] >= filtarar_por_qte_de_alelos
].reset_index(drop=True)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,AVHADMGYW,193,201,10,1.645,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
1,CTLPPLRYM,316,324,20,3.250,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
2,CTWPKSHTL,223,231,23,1.200,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
3,ECPSASRAW,142,150,10,2.150,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-B*3..."
4,ELKYSWKTW,110,118,11,1.500,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
5,EVHTWTEQY,24,32,16,1.500,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
6,EVHTWTEQYKF,24,34,10,3.250,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
7,FQADSPKRL,34,42,18,2.450,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
8,FTTNIWLKL,163,171,16,1.650,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
9,FVTNEVHTW,20,28,17,1.200,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
10,HTQTAGPWHL,261,270,10,3.100,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
11,HTWTEQYKF,26,34,21,1.500,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
12,IANELNYIL,71,79,14,1.650,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
13,ILWENNIKL,78,86,17,2.600,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
14,IVTAETQNSSF,123,133,10,3.850,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
15,IWLKLREVY,167,175,10,2.800,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3..."
16,KFQADSPKRL,33,42,10,2.800,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
17,KLREVYTQL,170,178,18,1.400,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
18,KQIANELNY,69,77,19,1.400,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
19,KSLAGPISQH,245,254,11,1.900,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
20,KTCTWPKSHTL,221,231,15,1.600,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
21,KTWGKAKIV,116,124,10,1.900,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3..."
22,KTWGKAKIVTA,116,126,10,2.550,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3..."
23,LIEVKTCTW,217,225,10,3.000,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
24,LTPQPMELKY,104,113,14,0.995,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
25,MEIRPISEK,333,341,11,2.300,"HLA-A*03:01, HLA-A*11:01, HLA-A*26:01, HLA-A*3..."
26,NEVHTWTEQY,23,32,10,1.600,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6..."
27,QPMELKYSW,107,115,16,0.570,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
28,QTAGPWHLGK,263,272,10,1.850,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
29,QTAGPWHLGKL,263,273,12,3.000,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
30,RAVHADMGY,192,200,12,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
31,RSCTLPPLR,314,322,10,1.950,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
32,RSCTLPPLRY,314,323,11,1.300,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
33,RTLTPQPMEL,102,111,17,2.300,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
34,RTLTPQPMELK,102,112,11,3.100,"HLA-A*01:01, HLA-A*02:01, HLA-A*03:01, HLA-A*1..."
35,RTLTPQPMELKY,102,113,13,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
36,SASRAWNVW,145,153,13,2.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
37,SCTLPPLRY,315,323,13,2.000,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
38,SLAGPISQH,246,254,16,2.350,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
39,SLAGPISQHNY,246,256,14,2.150,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1..."
40,SLIEVKTCTW,216,225,12,1.450,"HLA-A*02:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
41,SQHNYRPGY,252,260,14,1.285,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
42,SQKNGSWKL,204,212,15,1.200,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
43,TAETQNSSF,125,133,12,2.700,"HLA-A*01:01, HLA-A*26:01, HLA-B*07:02, HLA-B*0..."
44,TCTWPKSHTL,222,231,17,2.100,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
45,TLTPQPMEL,103,111,20,1.900,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
46,TLTPQPMELKY,103,113,11,1.300,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
47,TPQPMELKY,105,113,17,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
48,TPQPMELKYSW,105,115,12,2.450,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
49,TQTAGPWHL,262,270,14,1.850,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
50,TTRMENLLW,60,68,13,2.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
51,TTVSGKLIHEW,301,311,10,2.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
52,TVSGKLIHEW,302,311,12,2.150,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
53,TWPKSHTLW,224,232,11,1.200,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
54,VEDYGFGVF,155,163,11,3.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
55,VLEQGKRTL,96,104,10,2.300,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
56,VSGKLIHEW,303,311,13,1.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
57,VTAETQNSSF,124,133,12,1.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

## Sorting por median_biding_percentile

In [8]:
epitopos_repetidos = (
    epitopos_repetidos
    .sort_values(
        ["median_binding_percentile", "qte_de_alelos"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,QPMELKYSW,107,115,16,0.570,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
1,LTPQPMELKY,104,113,14,0.995,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
2,VSGKLIHEW,303,311,13,1.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
3,CTWPKSHTL,223,231,23,1.200,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
4,FVTNEVHTW,20,28,17,1.200,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
5,SQKNGSWKL,204,212,15,1.200,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
6,RTLTPQPMELKY,102,113,13,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
7,RAVHADMGY,192,200,12,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
8,TWPKSHTLW,224,232,11,1.200,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
9,SQHNYRPGY,252,260,14,1.285,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
10,RSCTLPPLRY,314,323,11,1.300,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
11,TLTPQPMELKY,103,113,11,1.300,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
12,KQIANELNY,69,77,19,1.400,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
13,KLREVYTQL,170,178,18,1.400,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
14,TPQPMELKY,105,113,17,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
15,SLIEVKTCTW,216,225,12,1.450,"HLA-A*02:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
16,HTWTEQYKF,26,34,21,1.500,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
17,EVHTWTEQY,24,32,16,1.500,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
18,ELKYSWKTW,110,118,11,1.500,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
19,KTCTWPKSHTL,221,231,15,1.600,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
20,VTAETQNSSF,124,133,12,1.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
21,NEVHTWTEQY,23,32,10,1.600,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6..."
22,AVHADMGYW,193,201,10,1.645,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
23,FTTNIWLKL,163,171,16,1.650,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
24,IANELNYIL,71,79,14,1.650,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
25,QTAGPWHLGK,263,272,10,1.850,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
26,TQTAGPWHL,262,270,14,1.850,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
27,TLTPQPMEL,103,111,20,1.900,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
28,KSLAGPISQH,245,254,11,1.900,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
29,KTWGKAKIV,116,124,10,1.900,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3..."
30,RSCTLPPLR,314,322,10,1.950,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
31,SCTLPPLRY,315,323,13,2.000,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
32,TCTWPKSHTL,222,231,17,2.100,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
33,TTVSGKLIHEW,301,311,10,2.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
34,SLAGPISQHNY,246,256,14,2.150,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1..."
35,ECPSASRAW,142,150,10,2.150,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-B*3..."
36,TVSGKLIHEW,302,311,12,2.150,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
37,RTLTPQPMEL,102,111,17,2.300,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
38,SASRAWNVW,145,153,13,2.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
39,MEIRPISEK,333,341,11,2.300,"HLA-A*03:01, HLA-A*11:01, HLA-A*26:01, HLA-A*3..."
40,VLEQGKRTL,96,104,10,2.300,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
41,SLAGPISQH,246,254,16,2.350,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
42,FQADSPKRL,34,42,18,2.450,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
43,TPQPMELKYSW,105,115,12,2.450,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
44,KTWGKAKIVTA,116,126,10,2.550,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3..."
45,ILWENNIKL,78,86,17,2.600,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
46,TTRMENLLW,60,68,13,2.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
47,TAETQNSSF,125,133,12,2.700,"HLA-A*01:01, HLA-A*26:01, HLA-B*07:02, HLA-B*0..."
48,IWLKLREVY,167,175,10,2.800,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3..."
49,KFQADSPKRL,33,42,10,2.800,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
50,QTAGPWHLGKL,263,273,12,3.000,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
51,LIEVKTCTW,217,225,10,3.000,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
52,HTQTAGPWHL,261,270,10,3.100,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
53,RTLTPQPMELK,102,112,11,3.100,"HLA-A*01:01, HLA-A*02:01, HLA-A*03:01, HLA-A*1..."
54,CTLPPLRYM,316,324,20,3.250,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
55,EVHTWTEQYKF,24,34,10,3.250,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
56,VEDYGFGVF,155,163,11,3.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
57,IVTAETQNSSF,123,133,10,3.850,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

## Separando epítopos e criando arquivo FASTA para IEDB analysis resource

In [9]:
pepitides = epitopos_repetidos.peptide

with open("./peptideos_tcell_1.fasta", "w") as f:
    for i, peptide in enumerate(pepitides, start=1):
        f.write(f">NP {i}\n")
        f.write(f"{peptide}\n")
        
pepitides

0        QPMELKYSW
1       LTPQPMELKY
2        VSGKLIHEW
3        CTWPKSHTL
4        FVTNEVHTW
5        SQKNGSWKL
6     RTLTPQPMELKY
7        RAVHADMGY
8        TWPKSHTLW
9        SQHNYRPGY
10      RSCTLPPLRY
11     TLTPQPMELKY
12       KQIANELNY
13       KLREVYTQL
14       TPQPMELKY
15      SLIEVKTCTW
16       HTWTEQYKF
17       EVHTWTEQY
18       ELKYSWKTW
19     KTCTWPKSHTL
20      VTAETQNSSF
21      NEVHTWTEQY
22       AVHADMGYW
23       FTTNIWLKL
24       IANELNYIL
25      QTAGPWHLGK
26       TQTAGPWHL
27       TLTPQPMEL
28      KSLAGPISQH
29       KTWGKAKIV
30       RSCTLPPLR
31       SCTLPPLRY
32      TCTWPKSHTL
33     TTVSGKLIHEW
34     SLAGPISQHNY
35       ECPSASRAW
36      TVSGKLIHEW
37      RTLTPQPMEL
38       SASRAWNVW
39       MEIRPISEK
40       VLEQGKRTL
41       SLAGPISQH
42       FQADSPKRL
43     TPQPMELKYSW
44     KTWGKAKIVTA
45       ILWENNIKL
46       TTRMENLLW
47       TAETQNSSF
48       IWLKLREVY
49      KFQADSPKRL
50     QTAGPWHLGKL
51       LIEVKTCTW
52      HTQTAGPWHL
53     RTLTPQPMELK
54       CTLPPLRYM
55     EVHTWTEQYKF
56       VEDYGFGVF
57     IVTAETQNSSF
Name: peptide, dtype: str

### Seqkit remove sequências proteicas contendo gaps e *.

In [10]:
# !seqkit grep -s -v -r -p '[-*]' './Fastas/denv1_NS1_proteinas.fa' > DENV1_seq_filter_all.fasta

### Resultado IEDB analysis resource

In [11]:
conservacy_result = pd.read_csv('./ConservancyResult_tcell_1.csv')
conservacy_result

,Epitope #,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,View details
0,1,NP 1,CTWPKSHTL,9,98.75% (630/638),88.89%,100.00%,NaN
1,2,NP 2,HTWTEQYKF,9,99.06% (632/638),88.89%,100.00%,NaN
2,3,NP 3,TLTPQPMEL,9,96.87% (618/638),55.56%,100.00%,NaN
3,4,NP 4,CTLPPLRYM,9,98.90% (631/638),77.78%,100.00%,NaN
4,5,NP 5,KQIANELNY,9,91.54% (584/638),77.78%,100.00%,NaN
5,6,NP 6,KLREVYTQL,9,46.08% (294/638),66.67%,100.00%,NaN
6,7,NP 7,FQADSPKRL,9,95.61% (610/638),88.89%,100.00%,NaN
7,8,NP 8,FVTNEVHTW,9,99.69% (636/638),88.89%,100.00%,NaN
8,9,NP 9,TPQPMELKY,9,97.96% (625/638),77.78%,100.00%,NaN
9,10,NP 10,TCTWPKSHTL,10,98.75% (630/638),90.00%,100.00%,NaN
10,11,NP 11,RTLTPQPMEL,10,96.55% (616/638),50.00%,100.00%,NaN
11,12,NP 12,ILWENNIKL,9,98.12% (626/638),55.56%,100.00%,NaN
12,13,NP 13,QPMELKYSW,9,99.22% (633/638),88.89%,100.00%,NaN
13,14,NP 14,EVHTWTEQY,9,99.37% (634/638),88.89%,100.00%,NaN
14,15,NP 15,FTTNIWLKL,9,94.20% (601/638),88.89%,100.00%,NaN
15,16,NP 16,SLAGPISQH,9,99.69% (636/638),66.67%,100.00%,NaN
16,17,NP 17,SQKNGSWKL,9,98.75% (630/638),66.67%,100.00%,NaN
17,18,NP 18,KTCTWPKSHTL,11,98.75% (630/638),90.91%,100.00%,NaN
18,19,NP 19,LTPQPMELKY,10,97.96% (625/638),70.00%,100.00%,NaN
19,20,NP 20,SQHNYRPGY,9,57.37% (366/638),88.89%,100.00%,NaN
20,21,NP 21,IANELNYIL,9,91.54% (584/638),77.78%,100.00%,NaN
21,22,NP 22,TQTAGPWHL,9,99.69% (636/638),88.89%,100.00%,NaN
22,23,NP 23,SLAGPISQHNY,11,57.21% (365/638),72.73%,100.00%,NaN
23,24,NP 24,VSGKLIHEW,9,99.53% (635/638),77.78%,100.00%,NaN
24,25,NP 25,RTLTPQPMELKY,12,96.55% (616/638),58.33%,100.00%,NaN
25,26,NP 26,SCTLPPLRY,9,99.69% (636/638),88.89%,100.00%,NaN
26,27,NP 27,SASRAWNVW,9,82.45% (526/638),55.56%,100.00%,NaN
27,28,NP 28,TTRMENLLW,9,99.22% (633/638),55.56%,100.00%,NaN
28,29,NP 29,RAVHADMGY,9,99.22% (633/638),88.89%,100.00%,NaN
29,30,NP 30,SLIEVKTCTW,10,81.97% (523/638),80.00%,100.00%,NaN
30,31,NP 31,VTAETQNSSF,10,97.18% (620/638),40.00%,100.00%,NaN
31,32,NP 32,TVSGKLIHEW,10,99.53% (635/638),80.00%,100.00%,NaN
32,33,NP 33,TPQPMELKYSW,11,97.96% (625/638),81.82%,100.00%,NaN
33,34,NP 34,TAETQNSSF,9,97.34% (621/638),44.44%,100.00%,NaN
34,35,NP 35,QTAGPWHLGKL,11,99.69% (636/638),90.91%,100.00%,NaN
35,36,NP 36,TWPKSHTLW,9,98.75% (630/638),88.89%,100.00%,NaN
36,37,NP 37,RSCTLPPLRY,10,99.69% (636/638),90.00%,100.00%,NaN
37,38,NP 38,TLTPQPMELKY,11,96.87% (618/638),63.64%,100.00%,NaN
38,39,NP 39,ELKYSWKTW,9,98.59% (629/638),77.78%,100.00%,NaN
39,40,NP 40,KSLAGPISQH,10,99.53% (635/638),70.00%,100.00%,NaN
40,41,NP 41,MEIRPISEK,9,61.13% (390/638),77.78%,100.00%,NaN
41,42,NP 42,RTLTPQPMELK,11,96.55% (616/638),54.55%,100.00%,NaN
42,43,NP 43,VEDYGFGVF,9,99.69% (636/638),88.89%,100.00%,NaN
43,44,NP 44,NEVHTWTEQY,10,99.37% (634/638),90.00%,100.00%,NaN
44,45,NP 45,AVHADMGYW,9,99.84% (637/638),88.89%,100.00%,NaN
45,46,NP 46,QTAGPWHLGK,10,99.69% (636/638),90.00%,100.00%,NaN
46,47,NP 47,KTWGKAKIV,9,96.71% (617/638),77.78%,100.00%,NaN
47,48,NP 48,RSCTLPPLR,9,100.00% (638/638),100.00%,100.00%,NaN
48,49,NP 49,TTVSGKLIHEW,11,99.53% (635/638),81.82%,100.00%,NaN
49,50,NP 50,ECPSASRAW,9,82.29% (525/638),66.67%,100.00%,NaN
50,51,NP 51,VLEQGKRTL,9,95.45% (609/638),44.44%,100.00%,NaN
51,52,NP 52,KTWGKAKIVTA,11,96.55% (616/638),72.73%,100.00%,NaN
52,53,NP 53,IWLKLREVY,9,72.10% (460/638),77.78%,100.00%,NaN
53,54,NP 54,KFQADSPKRL,10,95.14% (607/638),90.00%,100.00%,NaN
54,55,NP 55,LIEVKTCTW,9,81.97% (523/638),77.78%,100.00%,NaN
55,56,NP 56,HTQTAGPWHL,10,99.06% (632/638),90.00%,100.00%,NaN
56,57,NP 57,EVHTWTEQYKF,11,98.90% (631/638),90.91%,100.00%,NaN
57,58,NP 58,IVTAETQNSSF,11,96.71% (617/638),45.45%,100.00%,NaN

### Merge da coluna qte_de_alelos ao dataframe conservacy_result

In [12]:
# qte_de_alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "qte_de_alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("View details"))

# alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("Epitope #"))

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos
0,NP 1,CTWPKSHTL,9,98.75% (630/638),88.89%,100.00%,23,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
1,NP 2,HTWTEQYKF,9,99.06% (632/638),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
2,NP 3,TLTPQPMEL,9,96.87% (618/638),55.56%,100.00%,20,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
3,NP 4,CTLPPLRYM,9,98.90% (631/638),77.78%,100.00%,20,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
4,NP 5,KQIANELNY,9,91.54% (584/638),77.78%,100.00%,19,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
5,NP 6,KLREVYTQL,9,46.08% (294/638),66.67%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
6,NP 7,FQADSPKRL,9,95.61% (610/638),88.89%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
7,NP 8,FVTNEVHTW,9,99.69% (636/638),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
8,NP 9,TPQPMELKY,9,97.96% (625/638),77.78%,100.00%,17,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
9,NP 10,TCTWPKSHTL,10,98.75% (630/638),90.00%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
10,NP 11,RTLTPQPMEL,10,96.55% (616/638),50.00%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
11,NP 12,ILWENNIKL,9,98.12% (626/638),55.56%,100.00%,17,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
12,NP 13,QPMELKYSW,9,99.22% (633/638),88.89%,100.00%,16,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
13,NP 14,EVHTWTEQY,9,99.37% (634/638),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
14,NP 15,FTTNIWLKL,9,94.20% (601/638),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
15,NP 16,SLAGPISQH,9,99.69% (636/638),66.67%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
16,NP 17,SQKNGSWKL,9,98.75% (630/638),66.67%,100.00%,15,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
17,NP 18,KTCTWPKSHTL,11,98.75% (630/638),90.91%,100.00%,15,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
18,NP 19,LTPQPMELKY,10,97.96% (625/638),70.00%,100.00%,14,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
19,NP 20,SQHNYRPGY,9,57.37% (366/638),88.89%,100.00%,14,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
20,NP 21,IANELNYIL,9,91.54% (584/638),77.78%,100.00%,14,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
21,NP 22,TQTAGPWHL,9,99.69% (636/638),88.89%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
22,NP 23,SLAGPISQHNY,11,57.21% (365/638),72.73%,100.00%,14,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1..."
23,NP 24,VSGKLIHEW,9,99.53% (635/638),77.78%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
24,NP 25,RTLTPQPMELKY,12,96.55% (616/638),58.33%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
25,NP 26,SCTLPPLRY,9,99.69% (636/638),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
26,NP 27,SASRAWNVW,9,82.45% (526/638),55.56%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
27,NP 28,TTRMENLLW,9,99.22% (633/638),55.56%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
28,NP 29,RAVHADMGY,9,99.22% (633/638),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
29,NP 30,SLIEVKTCTW,10,81.97% (523/638),80.00%,100.00%,12,"HLA-A*02:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
30,NP 31,VTAETQNSSF,10,97.18% (620/638),40.00%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
31,NP 32,TVSGKLIHEW,10,99.53% (635/638),80.00%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
32,NP 33,TPQPMELKYSW,11,97.96% (625/638),81.82%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
33,NP 34,TAETQNSSF,9,97.34% (621/638),44.44%,100.00%,12,"HLA-A*01:01, HLA-A*26:01, HLA-B*07:02, HLA-B*0..."
34,NP 35,QTAGPWHLGKL,11,99.69% (636/638),90.91%,100.00%,12,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
35,NP 36,TWPKSHTLW,9,98.75% (630/638),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
36,NP 37,RSCTLPPLRY,10,99.69% (636/638),90.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
37,NP 38,TLTPQPMELKY,11,96.87% (618/638),63.64%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
38,NP 39,ELKYSWKTW,9,98.59% (629/638),77.78%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
39,NP 40,KSLAGPISQH,10,99.53% (635/638),70.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
40,NP 41,MEIRPISEK,9,61.13% (390/638),77.78%,100.00%,11,"HLA-A*03:01, HLA-A*11:01, HLA-A*26:01, HLA-A*3..."
41,NP 42,RTLTPQPMELK,11,96.55% (616/638),54.55%,100.00%,11,"HLA-A*01:01, HLA-A*02:01, HLA-A*03:01, HLA-A*1..."
42,NP 43,VEDYGFGVF,9,99.69% (636/638),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
43,NP 44,NEVHTWTEQY,10,99.37% (634/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6..."
44,NP 45,AVHADMGYW,9,99.84% (637/638),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
45,NP 46,QTAGPWHLGK,10,99.69% (636/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
46,NP 47,KTWGKAKIV,9,96.71% (617/638),77.78%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3..."
47,NP 48,RSCTLPPLR,9,100.00% (638/638),100.00%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
48,NP 49,TTVSGKLIHEW,11,99.53% (635/638),81.82%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
49,NP 50,ECPSASRAW,9,82.29% (525/638),66.67%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-B*3..."
50,NP 51,VLEQGKRTL,9,95.45% (609/638),44.44%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
51,NP 52,KTWGKAKIVTA,11,96.55% (616/638),72.73%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3..."
52,NP 53,IWLKLREVY,9,72.10% (460/638),77.78%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3..."
53,NP 54,KFQADSPKRL,10,95.14% (607/638),90.00%,100.00%,10,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
54,NP 55,LIEVKTCTW,9,81.97% (523/638),77.78%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
55,NP 56,HTQTAGPWHL,10,99.06% (632/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
56,NP 57,EVHTWTEQYKF,11,98.90% (631/638),90.91%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
57,NP 58,IVTAETQNSSF,11,96.71% (617/638),45.45%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

### Gerando a coluna percent_match para filtrar os epitopos com percentagem de match maior que 50%

In [13]:
col = "Percent of protein sequence matches at identity <= 100%"

conservacy_result["percent_match"] = (
    conservacy_result[col]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
    .astype(float)
)

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos,percent_match
0,NP 1,CTWPKSHTL,9,98.75% (630/638),88.89%,100.00%,23,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",98.75
1,NP 2,HTWTEQYKF,9,99.06% (632/638),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2...",99.06
2,NP 3,TLTPQPMEL,9,96.87% (618/638),55.56%,100.00%,20,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",96.87
3,NP 4,CTLPPLRYM,9,98.90% (631/638),77.78%,100.00%,20,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",98.90
4,NP 5,KQIANELNY,9,91.54% (584/638),77.78%,100.00%,19,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",91.54
5,NP 6,KLREVYTQL,9,46.08% (294/638),66.67%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0...",46.08
6,NP 7,FQADSPKRL,9,95.61% (610/638),88.89%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",95.61
7,NP 8,FVTNEVHTW,9,99.69% (636/638),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2...",99.69
8,NP 9,TPQPMELKY,9,97.96% (625/638),77.78%,100.00%,17,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.96
9,NP 10,TCTWPKSHTL,10,98.75% (630/638),90.00%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",98.75
10,NP 11,RTLTPQPMEL,10,96.55% (616/638),50.00%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",96.55
11,NP 12,ILWENNIKL,9,98.12% (626/638),55.56%,100.00%,17,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",98.12
12,NP 13,QPMELKYSW,9,99.22% (633/638),88.89%,100.00%,16,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",99.22
13,NP 14,EVHTWTEQY,9,99.37% (634/638),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.37
14,NP 15,FTTNIWLKL,9,94.20% (601/638),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",94.20
15,NP 16,SLAGPISQH,9,99.69% (636/638),66.67%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",99.69
16,NP 17,SQKNGSWKL,9,98.75% (630/638),66.67%,100.00%,15,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",98.75
17,NP 18,KTCTWPKSHTL,11,98.75% (630/638),90.91%,100.00%,15,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",98.75
18,NP 19,LTPQPMELKY,10,97.96% (625/638),70.00%,100.00%,14,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.96
19,NP 20,SQHNYRPGY,9,57.37% (366/638),88.89%,100.00%,14,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",57.37
20,NP 21,IANELNYIL,9,91.54% (584/638),77.78%,100.00%,14,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",91.54
21,NP 22,TQTAGPWHL,9,99.69% (636/638),88.89%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",99.69
22,NP 23,SLAGPISQHNY,11,57.21% (365/638),72.73%,100.00%,14,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1...",57.21
23,NP 24,VSGKLIHEW,9,99.53% (635/638),77.78%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.53
24,NP 25,RTLTPQPMELKY,12,96.55% (616/638),58.33%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",96.55
25,NP 26,SCTLPPLRY,9,99.69% (636/638),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.69
26,NP 27,SASRAWNVW,9,82.45% (526/638),55.56%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",82.45
27,NP 28,TTRMENLLW,9,99.22% (633/638),55.56%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.22
28,NP 29,RAVHADMGY,9,99.22% (633/638),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.22
29,NP 30,SLIEVKTCTW,10,81.97% (523/638),80.00%,100.00%,12,"HLA-A*02:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",81.97
30,NP 31,VTAETQNSSF,10,97.18% (620/638),40.00%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.18
31,NP 32,TVSGKLIHEW,10,99.53% (635/638),80.00%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.53
32,NP 33,TPQPMELKYSW,11,97.96% (625/638),81.82%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0...",97.96
33,NP 34,TAETQNSSF,9,97.34% (621/638),44.44%,100.00%,12,"HLA-A*01:01, HLA-A*26:01, HLA-B*07:02, HLA-B*0...",97.34
34,NP 35,QTAGPWHLGKL,11,99.69% (636/638),90.91%,100.00%,12,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",99.69
35,NP 36,TWPKSHTLW,9,98.75% (630/638),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",98.75
36,NP 37,RSCTLPPLRY,10,99.69% (636/638),90.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.69
37,NP 38,TLTPQPMELKY,11,96.87% (618/638),63.64%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",96.87
38,NP 39,ELKYSWKTW,9,98.59% (629/638),77.78%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",98.59
39,NP 40,KSLAGPISQH,10,99.53% (635/638),70.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.53
40,NP 41,MEIRPISEK,9,61.13% (390/638),77.78%,100.00%,11,"HLA-A*03:01, HLA-A*11:01, HLA-A*26:01, HLA-A*3...",61.13
41,NP 42,RTLTPQPMELK,11,96.55% (616/638),54.55%,100.00%,11,"HLA-A*01:01, HLA-A*02:01, HLA-A*03:01, HLA-A*1...",96.55
42,NP 43,VEDYGFGVF,9,99.69% (636/638),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.69
43,NP 44,NEVHTWTEQY,10,99.37% (634/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6...",99.37
44,NP 45,AVHADMGYW,9,99.84% (637/638),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3...",99.84
45,NP 46,QTAGPWHLGK,10,99.69% (636/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.69
46,NP 47,KTWGKAKIV,9,96.71% (617/638),77.78%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3...",96.71
47,NP 48,RSCTLPPLR,9,100.00% (638/638),100.00%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",100.00
48,NP 49,TTVSGKLIHEW,11,99.53% (635/638),81.82%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.53
49,NP 50,ECPSASRAW,9,82.29% (525/638),66.67%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-B*3...",82.29
50,NP 51,VLEQGKRTL,9,95.45% (609/638),44.44%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",95.45
51,NP 52,KTWGKAKIVTA,11,96.55% (616/638),72.73%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3...",96.55
52,NP 53,IWLKLREVY,9,72.10% (460/638),77.78%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3...",72.10
53,NP 54,KFQADSPKRL,10,95.14% (607/638),90.00%,100.00%,10,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",95.14
54,NP 55,LIEVKTCTW,9,81.97% (523/638),77.78%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3...",81.97
55,NP 56,HTQTAGPWHL,10,99.06% (632/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",99.06
56,NP 57,EVHTWTEQYKF,11,98.90% (631/638),90.91%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",98.90
57,NP 58,IVTAETQNSSF,11,96.71% (617/638),45.45%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",96.71

### Sort e filtragem por percent_match e presença em alelos

In [14]:
# Parametros
percent_match_minimo = 95.0

In [15]:
# Filtro do Percent match
conservacy_result_filtered = (
    conservacy_result[conservacy_result["percent_match"] >= percent_match_minimo]
    .sort_values(
            by="percent_match", 
            ascending=False
        )
    ).reset_index(drop=True)

conservacy_result_filtered

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos,percent_match
0,NP 48,RSCTLPPLR,9,100.00% (638/638),100.00%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",100.00
1,NP 45,AVHADMGYW,9,99.84% (637/638),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3...",99.84
2,NP 26,SCTLPPLRY,9,99.69% (636/638),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.69
3,NP 22,TQTAGPWHL,9,99.69% (636/638),88.89%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",99.69
4,NP 8,FVTNEVHTW,9,99.69% (636/638),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2...",99.69
5,NP 16,SLAGPISQH,9,99.69% (636/638),66.67%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",99.69
6,NP 37,RSCTLPPLRY,10,99.69% (636/638),90.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.69
7,NP 35,QTAGPWHLGKL,11,99.69% (636/638),90.91%,100.00%,12,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",99.69
8,NP 46,QTAGPWHLGK,10,99.69% (636/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.69
9,NP 43,VEDYGFGVF,9,99.69% (636/638),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.69
10,NP 49,TTVSGKLIHEW,11,99.53% (635/638),81.82%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.53
11,NP 40,KSLAGPISQH,10,99.53% (635/638),70.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.53
12,NP 32,TVSGKLIHEW,10,99.53% (635/638),80.00%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.53
13,NP 24,VSGKLIHEW,9,99.53% (635/638),77.78%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.53
14,NP 44,NEVHTWTEQY,10,99.37% (634/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6...",99.37
15,NP 14,EVHTWTEQY,9,99.37% (634/638),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.37
16,NP 13,QPMELKYSW,9,99.22% (633/638),88.89%,100.00%,16,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",99.22
17,NP 29,RAVHADMGY,9,99.22% (633/638),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.22
18,NP 28,TTRMENLLW,9,99.22% (633/638),55.56%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.22
19,NP 2,HTWTEQYKF,9,99.06% (632/638),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2...",99.06
20,NP 56,HTQTAGPWHL,10,99.06% (632/638),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",99.06
21,NP 57,EVHTWTEQYKF,11,98.90% (631/638),90.91%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",98.90
22,NP 4,CTLPPLRYM,9,98.90% (631/638),77.78%,100.00%,20,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",98.90
23,NP 18,KTCTWPKSHTL,11,98.75% (630/638),90.91%,100.00%,15,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",98.75
24,NP 36,TWPKSHTLW,9,98.75% (630/638),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",98.75
25,NP 17,SQKNGSWKL,9,98.75% (630/638),66.67%,100.00%,15,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",98.75
26,NP 10,TCTWPKSHTL,10,98.75% (630/638),90.00%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",98.75
27,NP 1,CTWPKSHTL,9,98.75% (630/638),88.89%,100.00%,23,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",98.75
28,NP 39,ELKYSWKTW,9,98.59% (629/638),77.78%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",98.59
29,NP 12,ILWENNIKL,9,98.12% (626/638),55.56%,100.00%,17,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",98.12
30,NP 19,LTPQPMELKY,10,97.96% (625/638),70.00%,100.00%,14,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.96
31,NP 33,TPQPMELKYSW,11,97.96% (625/638),81.82%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0...",97.96
32,NP 9,TPQPMELKY,9,97.96% (625/638),77.78%,100.00%,17,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.96
33,NP 34,TAETQNSSF,9,97.34% (621/638),44.44%,100.00%,12,"HLA-A*01:01, HLA-A*26:01, HLA-B*07:02, HLA-B*0...",97.34
34,NP 31,VTAETQNSSF,10,97.18% (620/638),40.00%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.18
35,NP 38,TLTPQPMELKY,11,96.87% (618/638),63.64%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",96.87
36,NP 3,TLTPQPMEL,9,96.87% (618/638),55.56%,100.00%,20,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",96.87
37,NP 58,IVTAETQNSSF,11,96.71% (617/638),45.45%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",96.71
38,NP 47,KTWGKAKIV,9,96.71% (617/638),77.78%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3...",96.71
39,NP 11,RTLTPQPMEL,10,96.55% (616/638),50.00%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",96.55
40,NP 42,RTLTPQPMELK,11,96.55% (616/638),54.55%,100.00%,11,"HLA-A*01:01, HLA-A*02:01, HLA-A*03:01, HLA-A*1...",96.55
41,NP 25,RTLTPQPMELKY,12,96.55% (616/638),58.33%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",96.55
42,NP 52,KTWGKAKIVTA,11,96.55% (616/638),72.73%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*3...",96.55
43,NP 7,FQADSPKRL,9,95.61% (610/638),88.89%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",95.61
44,NP 51,VLEQGKRTL,9,95.45% (609/638),44.44%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",95.45
45,NP 54,KFQADSPKRL,10,95.14% (607/638),90.00%,100.00%,10,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",95.14