# Análise de dados TCP-CII

### Importação dos parâmetros universais

In [22]:
import importlib.util
from pathlib import Path

path = Path("../../../parametros/config.py").resolve()

spec = importlib.util.spec_from_file_location("parametros", path)
parametros = importlib.util.module_from_spec(spec)
spec.loader.exec_module(parametros)

In [23]:
# Parâmetros importados do arquivo config.py
print(
    "Filtrar por quantidade de alelos TCC2:.........................",
    parametros.filtarar_por_qte_de_alelos_tcc2,
)
print(
    "Parâmetro de filtragem median binding percentile TCC2:.........",
    parametros.parametro_de_filtragem_mbp_tcc2,
)
print(
    "Percentual de match mínimo TCC2:...............................",
    parametros.percent_match_minimo_tcc2,
)

Filtrar por quantidade de alelos TCC2:......................... 2
Parâmetro de filtragem median binding percentile TCC2:......... 1
Percentual de match mínimo TCC2:............................... 95.0

In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('./T CELL/DENV 3 - T Cell Prediction - Class II.csv')
df

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhciipan_el core,netmhciipan_el score,netmhciipan_el percentile
0,1,KNGSWKLEKASLIEVK,206,221,16,HLA-DRB1*01:01,246,0.02,WKLEKASLI,0.983079,0.02
1,1,QYKFQADSPKRLA,31,43,13,HLA-DRB3*01:01,7,0.05,FQADSPKRL,0.927520,0.05
2,1,KNGSWKLEKASLIEVKT,206,222,17,HLA-DRB1*01:01,314,0.06,WKLEKASLI,0.972226,0.06
3,1,QYKFQADSPKRLAT,31,44,14,HLA-DRB3*01:01,75,0.06,FQADSPKRL,0.921728,0.06
4,1,KNGSWKLEKASLIEVKTC,206,223,18,HLA-DRB1*01:01,382,0.07,WKLEKASLI,0.950728,0.07
...,...,...,...,...,...,...,...,...,...,...,...
16411,1,KLIHEWCCRSCTLPPLRYMGE,306,326,21,HLA-DRB3*02:02,603,100.00,CTLPPLRYM,0.000019,100.00
16412,1,KLIHEWCCRSCTLPPLRYMG,306,325,20,HLA-DRB1*04:01,536,100.00,CRSCTLPPL,0.000018,100.00
16413,1,KLIHEWCCRSCTLPPLRYMGE,306,326,21,HLA-DRB1*04:01,603,100.00,CRSCTLPPL,0.000015,100.00
16414,1,TTVSGKLIHEWCC,301,313,13,HLA-DRB3*02:02,61,100.00,VSGKLIHEW,0.000013,100.00
16415,1,TTVSGKLIHEWCCRSCTLPPL,301,321,21,HLA-DRB3*02:02,602,100.00,LIHEWCCRS,0.000011,100.00

## Selecionando Epítopos por median binding percentile.

In [26]:
mbp_minimo = parametros.parametro_de_filtragem_mbp_tcc2

In [27]:
df_mbp_m5 = df[df['median binding percentile'] < mbp_minimo].copy()
print("Filtrando por median binding percentile < ", mbp_minimo)
df_mbp_m5

Filtrando por median binding percentile <  1

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhciipan_el core,netmhciipan_el score,netmhciipan_el percentile
0,1,KNGSWKLEKASLIEVK,206,221,16,HLA-DRB1*01:01,246,0.02,WKLEKASLI,0.983079,0.02
1,1,QYKFQADSPKRLA,31,43,13,HLA-DRB3*01:01,7,0.05,FQADSPKRL,0.927520,0.05
2,1,KNGSWKLEKASLIEVKT,206,222,17,HLA-DRB1*01:01,314,0.06,WKLEKASLI,0.972226,0.06
3,1,QYKFQADSPKRLAT,31,44,14,HLA-DRB3*01:01,75,0.06,FQADSPKRL,0.921728,0.06
4,1,KNGSWKLEKASLIEVKTC,206,223,18,HLA-DRB1*01:01,382,0.07,WKLEKASLI,0.950728,0.07
...,...,...,...,...,...,...,...,...,...,...,...
95,1,ERAVHADMGYWIE,191,203,13,HLA-DRB3*01:01,39,0.96,VHADMGYWI,0.377244,0.96
96,1,SSFIIDGPNTPEC,131,143,13,HLA-DRB3*01:01,27,0.96,FIIDGPNTP,0.373759,0.96
97,1,AETQNSSFIIDGPNTPECPS,126,145,20,HLA-DRB3*01:01,500,0.98,FIIDGPNTP,0.271350,0.98
98,1,ERAVHADMGYWIESQ,191,205,15,HLA-DRB3*01:01,175,0.99,VHADMGYWI,0.475558,0.99
99,1,HTWTEQYKFQADSPKRLATAI,26,46,21,HLA-DRB5*01:01,547,0.99,YKFQADSPK,0.250150,0.99

## Agrupando por pepitideos e agregando colunas pertinentes

In [28]:
epitopos_repetidos = (
    df_mbp_m5
    .groupby('peptide', as_index=False)
    .agg(
        start=("start", "first"),
        end=("end", "first"),
        qte_de_alelos=("allele", "nunique"),
        median_binding_percentile=(
            "median binding percentile",
            "median"
        ),
        alelos=(
            "allele",
            lambda x: ", ".join(sorted(x.unique()))
        )
    )
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,ADSPKRLATAIAGAW,36,50,1,0.85,HLA-DPA1*02:01/DPB1*14:01
1,ADSPKRLATAIAGAWE,36,51,1,0.40,HLA-DPA1*02:01/DPB1*14:01
2,ADSPKRLATAIAGAWEN,36,52,1,0.23,HLA-DPA1*02:01/DPB1*14:01
3,ADSPKRLATAIAGAWENG,36,53,1,0.32,HLA-DPA1*02:01/DPB1*14:01
4,ADSPKRLATAIAGAWENGV,36,54,1,0.43,HLA-DPA1*02:01/DPB1*14:01
...,...,...,...,...,...,...
73,YRPGYHTQTAGPWHLGK,256,272,1,0.20,HLA-DQA1*05:01/DQB1*02:01
74,YRPGYHTQTAGPWHLGKL,256,273,1,0.25,HLA-DQA1*05:01/DQB1*02:01
75,YRPGYHTQTAGPWHLGKLE,256,274,1,0.29,HLA-DQA1*05:01/DQB1*02:01
76,YRPGYHTQTAGPWHLGKLEL,256,275,1,0.35,HLA-DQA1*05:01/DQB1*02:01
77,YRPGYHTQTAGPWHLGKLELD,256,276,1,0.36,HLA-DQA1*05:01/DQB1*02:01

## Filtragem por qte_de_alelos

In [29]:
# mbp_minimo = 1
qte_alelos_minimo = parametros.filtarar_por_qte_de_alelos_tcc2

In [30]:
# Filtro do número de alelos
epitopos_repetidos = epitopos_repetidos[
    epitopos_repetidos["qte_de_alelos"] >= qte_alelos_minimo
].reset_index(drop=True)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,GVFTTNIWLKLRE,161,173,4,0.365,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
1,GVFTTNIWLKLREV,161,174,4,0.835,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
2,HTWTEQYKFQADSPKRL,26,42,2,0.755,"HLA-DRB3*01:01, HLA-DRB5*01:01"
3,HTWTEQYKFQADSPKRLA,26,43,2,0.315,"HLA-DRB3*01:01, HLA-DRB5*01:01"
4,HTWTEQYKFQADSPKRLAT,26,44,2,0.400,"HLA-DRB3*01:01, HLA-DRB5*01:01"
5,HTWTEQYKFQADSPKRLATA,26,45,3,0.860,"HLA-DRB3*01:01, HLA-DRB3*02:02, HLA-DRB5*01:01"
6,HTWTEQYKFQADSPKRLATAI,26,46,2,0.575,"HLA-DRB3*01:01, HLA-DRB5*01:01"
7,KNGSWKLEKASLIEVK,206,221,3,0.800,"HLA-DRB1*01:01, HLA-DRB1*07:01, HLA-DRB3*02:02"
8,QYKFQADSPKRLA,31,43,2,0.240,"HLA-DRB3*01:01, HLA-DRB3*02:02"
9,QYKFQADSPKRLAT,31,44,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02"
10,QYKFQADSPKRLATA,31,45,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02"
11,QYKFQADSPKRLATAI,31,46,2,0.445,"HLA-DRB3*01:01, HLA-DRB3*02:02"
12,YRPGYHTQTAGPW,256,268,2,0.330,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
13,YRPGYHTQTAGPWH,256,269,2,0.245,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
14,YRPGYHTQTAGPWHL,256,270,2,0.555,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
15,YRPGYHTQTAGPWHLG,256,271,2,0.410,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."

## Sorting por median_biding_percentile

In [31]:
epitopos_repetidos = (
    epitopos_repetidos
    .sort_values(
        ["median_binding_percentile", "qte_de_alelos"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,QYKFQADSPKRLA,31,43,2,0.240,"HLA-DRB3*01:01, HLA-DRB3*02:02"
1,YRPGYHTQTAGPWH,256,269,2,0.245,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
2,HTWTEQYKFQADSPKRLA,26,43,2,0.315,"HLA-DRB3*01:01, HLA-DRB5*01:01"
3,YRPGYHTQTAGPW,256,268,2,0.330,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
4,QYKFQADSPKRLAT,31,44,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02"
5,QYKFQADSPKRLATA,31,45,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02"
6,GVFTTNIWLKLRE,161,173,4,0.365,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
7,HTWTEQYKFQADSPKRLAT,26,44,2,0.400,"HLA-DRB3*01:01, HLA-DRB5*01:01"
8,YRPGYHTQTAGPWHLG,256,271,2,0.410,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
9,QYKFQADSPKRLATAI,31,46,2,0.445,"HLA-DRB3*01:01, HLA-DRB3*02:02"
10,YRPGYHTQTAGPWHL,256,270,2,0.555,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
11,HTWTEQYKFQADSPKRLATAI,26,46,2,0.575,"HLA-DRB3*01:01, HLA-DRB5*01:01"
12,HTWTEQYKFQADSPKRL,26,42,2,0.755,"HLA-DRB3*01:01, HLA-DRB5*01:01"
13,KNGSWKLEKASLIEVK,206,221,3,0.800,"HLA-DRB1*01:01, HLA-DRB1*07:01, HLA-DRB3*02:02"
14,GVFTTNIWLKLREV,161,174,4,0.835,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
15,HTWTEQYKFQADSPKRLATA,26,45,3,0.860,"HLA-DRB3*01:01, HLA-DRB3*02:02, HLA-DRB5*01:01"

## Separando epítopos e criando arquivo FASTA para IEDB analysis resource

In [32]:
pepitides = epitopos_repetidos.peptide

with open("./peptideos_tcell_2.fasta", "w") as f:
    for i, peptide in enumerate(pepitides, start=1):
        f.write(f">NP {i}\n")
        f.write(f"{peptide}\n")
        
pepitides

0             QYKFQADSPKRLA
1            YRPGYHTQTAGPWH
2        HTWTEQYKFQADSPKRLA
3             YRPGYHTQTAGPW
4            QYKFQADSPKRLAT
5           QYKFQADSPKRLATA
6             GVFTTNIWLKLRE
7       HTWTEQYKFQADSPKRLAT
8          YRPGYHTQTAGPWHLG
9          QYKFQADSPKRLATAI
10          YRPGYHTQTAGPWHL
11    HTWTEQYKFQADSPKRLATAI
12        HTWTEQYKFQADSPKRL
13         KNGSWKLEKASLIEVK
14           GVFTTNIWLKLREV
15     HTWTEQYKFQADSPKRLATA
Name: peptide, dtype: str

### Seqkit remove sequências proteicas contendo gaps e *.

In [33]:
# !seqkit grep -s -v -r -p '[-*]' './Fastas/denv1_NS1_proteinas.fa' > DENV1_seq_filter_all.fasta

### Resultado IEDB analysis resource

In [34]:
conservacy_result = pd.read_csv('./ConservancyResult_tcell_2.csv')
conservacy_result

,Epitope #,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,View details
0,1,NP 1,QYKFQADSPKRLA,13,94.83% (605/638),84.62%,100.00%,NaN
1,2,NP 2,YRPGYHTQTAGPWH,14,57.05% (364/638),85.71%,100.00%,NaN
2,3,NP 3,HTWTEQYKFQADSPKRLA,18,94.51% (603/638),88.89%,100.00%,NaN
3,4,NP 4,YRPGYHTQTAGPW,13,57.05% (364/638),84.62%,100.00%,NaN
4,5,NP 5,QYKFQADSPKRLAT,14,94.83% (605/638),78.57%,100.00%,NaN
5,6,NP 6,QYKFQADSPKRLATA,15,94.83% (605/638),80.00%,100.00%,NaN
6,7,NP 7,GVFTTNIWLKLRE,13,93.57% (597/638),84.62%,100.00%,NaN
7,8,NP 8,HTWTEQYKFQADSPKRLAT,19,94.51% (603/638),84.21%,100.00%,NaN
8,9,NP 9,YRPGYHTQTAGPWHLG,16,57.05% (364/638),87.50%,100.00%,NaN
9,10,NP 10,QYKFQADSPKRLATAI,16,94.83% (605/638),81.25%,100.00%,NaN
10,11,NP 11,YRPGYHTQTAGPWHL,15,57.05% (364/638),86.67%,100.00%,NaN
11,12,NP 12,HTWTEQYKFQADSPKRLATAI,21,94.51% (603/638),85.71%,100.00%,NaN
12,13,NP 13,HTWTEQYKFQADSPKRL,17,94.67% (604/638),94.12%,100.00%,NaN
13,14,NP 14,KNGSWKLEKASLIEVK,16,81.03% (517/638),68.75%,100.00%,NaN
14,15,NP 15,GVFTTNIWLKLREV,14,72.88% (465/638),78.57%,100.00%,NaN
15,16,NP 16,HTWTEQYKFQADSPKRLATA,20,94.51% (603/638),85.00%,100.00%,NaN

### Merge da coluna qte_de_alelos ao dataframe conservacy_result

In [35]:
# qte_de_alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "qte_de_alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("View details"))

# qte_de_alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "median_binding_percentile"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide"))

# alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("Epitope #"))

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,median_binding_percentile,alelos
0,NP 1,QYKFQADSPKRLA,13,94.83% (605/638),84.62%,100.00%,2,0.240,"HLA-DRB3*01:01, HLA-DRB3*02:02"
1,NP 2,YRPGYHTQTAGPWH,14,57.05% (364/638),85.71%,100.00%,2,0.245,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
2,NP 3,HTWTEQYKFQADSPKRLA,18,94.51% (603/638),88.89%,100.00%,2,0.315,"HLA-DRB3*01:01, HLA-DRB5*01:01"
3,NP 4,YRPGYHTQTAGPW,13,57.05% (364/638),84.62%,100.00%,2,0.330,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
4,NP 5,QYKFQADSPKRLAT,14,94.83% (605/638),78.57%,100.00%,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02"
5,NP 6,QYKFQADSPKRLATA,15,94.83% (605/638),80.00%,100.00%,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02"
6,NP 7,GVFTTNIWLKLRE,13,93.57% (597/638),84.62%,100.00%,4,0.365,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
7,NP 8,HTWTEQYKFQADSPKRLAT,19,94.51% (603/638),84.21%,100.00%,2,0.400,"HLA-DRB3*01:01, HLA-DRB5*01:01"
8,NP 9,YRPGYHTQTAGPWHLG,16,57.05% (364/638),87.50%,100.00%,2,0.410,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
9,NP 10,QYKFQADSPKRLATAI,16,94.83% (605/638),81.25%,100.00%,2,0.445,"HLA-DRB3*01:01, HLA-DRB3*02:02"
10,NP 11,YRPGYHTQTAGPWHL,15,57.05% (364/638),86.67%,100.00%,2,0.555,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
11,NP 12,HTWTEQYKFQADSPKRLATAI,21,94.51% (603/638),85.71%,100.00%,2,0.575,"HLA-DRB3*01:01, HLA-DRB5*01:01"
12,NP 13,HTWTEQYKFQADSPKRL,17,94.67% (604/638),94.12%,100.00%,2,0.755,"HLA-DRB3*01:01, HLA-DRB5*01:01"
13,NP 14,KNGSWKLEKASLIEVK,16,81.03% (517/638),68.75%,100.00%,3,0.800,"HLA-DRB1*01:01, HLA-DRB1*07:01, HLA-DRB3*02:02"
14,NP 15,GVFTTNIWLKLREV,14,72.88% (465/638),78.57%,100.00%,4,0.835,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
15,NP 16,HTWTEQYKFQADSPKRLATA,20,94.51% (603/638),85.00%,100.00%,3,0.860,"HLA-DRB3*01:01, HLA-DRB3*02:02, HLA-DRB5*01:01"

### Gerando a coluna percent_match para filtrar os epitopos com percentagem de match maior que 50%

In [36]:
col = "Percent of protein sequence matches at identity <= 100%"

conservacy_result["percent_match"] = (
    conservacy_result[col]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
    .astype(float)
)

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,median_binding_percentile,alelos,percent_match
0,NP 1,QYKFQADSPKRLA,13,94.83% (605/638),84.62%,100.00%,2,0.240,"HLA-DRB3*01:01, HLA-DRB3*02:02",94.83
1,NP 2,YRPGYHTQTAGPWH,14,57.05% (364/638),85.71%,100.00%,2,0.245,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1...",57.05
2,NP 3,HTWTEQYKFQADSPKRLA,18,94.51% (603/638),88.89%,100.00%,2,0.315,"HLA-DRB3*01:01, HLA-DRB5*01:01",94.51
3,NP 4,YRPGYHTQTAGPW,13,57.05% (364/638),84.62%,100.00%,2,0.330,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1...",57.05
4,NP 5,QYKFQADSPKRLAT,14,94.83% (605/638),78.57%,100.00%,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02",94.83
5,NP 6,QYKFQADSPKRLATA,15,94.83% (605/638),80.00%,100.00%,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02",94.83
6,NP 7,GVFTTNIWLKLRE,13,93.57% (597/638),84.62%,100.00%,4,0.365,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1...",93.57
7,NP 8,HTWTEQYKFQADSPKRLAT,19,94.51% (603/638),84.21%,100.00%,2,0.400,"HLA-DRB3*01:01, HLA-DRB5*01:01",94.51
8,NP 9,YRPGYHTQTAGPWHLG,16,57.05% (364/638),87.50%,100.00%,2,0.410,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1...",57.05
9,NP 10,QYKFQADSPKRLATAI,16,94.83% (605/638),81.25%,100.00%,2,0.445,"HLA-DRB3*01:01, HLA-DRB3*02:02",94.83
10,NP 11,YRPGYHTQTAGPWHL,15,57.05% (364/638),86.67%,100.00%,2,0.555,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1...",57.05
11,NP 12,HTWTEQYKFQADSPKRLATAI,21,94.51% (603/638),85.71%,100.00%,2,0.575,"HLA-DRB3*01:01, HLA-DRB5*01:01",94.51
12,NP 13,HTWTEQYKFQADSPKRL,17,94.67% (604/638),94.12%,100.00%,2,0.755,"HLA-DRB3*01:01, HLA-DRB5*01:01",94.67
13,NP 14,KNGSWKLEKASLIEVK,16,81.03% (517/638),68.75%,100.00%,3,0.800,"HLA-DRB1*01:01, HLA-DRB1*07:01, HLA-DRB3*02:02",81.03
14,NP 15,GVFTTNIWLKLREV,14,72.88% (465/638),78.57%,100.00%,4,0.835,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1...",72.88
15,NP 16,HTWTEQYKFQADSPKRLATA,20,94.51% (603/638),85.00%,100.00%,3,0.860,"HLA-DRB3*01:01, HLA-DRB3*02:02, HLA-DRB5*01:01",94.51

### Sort e filtragem por percent_match

In [39]:
# Minimum percentage of match for T Cell prediction
# minimum_percent_match = parametros.percent_match_minimo_tcc2
minimum_percent_match = 94

In [40]:
# Filtro do Percent match
conservacy_result_filtered = (
    conservacy_result[conservacy_result["percent_match"] >= minimum_percent_match]
    .sort_values(
            by="percent_match", 
            ascending=False
        )
    ).reset_index(drop=True)

conservacy_result_filtered

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,median_binding_percentile,alelos,percent_match
0,NP 1,QYKFQADSPKRLA,13,94.83% (605/638),84.62%,100.00%,2,0.240,"HLA-DRB3*01:01, HLA-DRB3*02:02",94.83
1,NP 5,QYKFQADSPKRLAT,14,94.83% (605/638),78.57%,100.00%,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02",94.83
2,NP 6,QYKFQADSPKRLATA,15,94.83% (605/638),80.00%,100.00%,2,0.340,"HLA-DRB3*01:01, HLA-DRB3*02:02",94.83
3,NP 10,QYKFQADSPKRLATAI,16,94.83% (605/638),81.25%,100.00%,2,0.445,"HLA-DRB3*01:01, HLA-DRB3*02:02",94.83
4,NP 13,HTWTEQYKFQADSPKRL,17,94.67% (604/638),94.12%,100.00%,2,0.755,"HLA-DRB3*01:01, HLA-DRB5*01:01",94.67
5,NP 8,HTWTEQYKFQADSPKRLAT,19,94.51% (603/638),84.21%,100.00%,2,0.400,"HLA-DRB3*01:01, HLA-DRB5*01:01",94.51
6,NP 3,HTWTEQYKFQADSPKRLA,18,94.51% (603/638),88.89%,100.00%,2,0.315,"HLA-DRB3*01:01, HLA-DRB5*01:01",94.51
7,NP 12,HTWTEQYKFQADSPKRLATAI,21,94.51% (603/638),85.71%,100.00%,2,0.575,"HLA-DRB3*01:01, HLA-DRB5*01:01",94.51
8,NP 16,HTWTEQYKFQADSPKRLATA,20,94.51% (603/638),85.00%,100.00%,3,0.860,"HLA-DRB3*01:01, HLA-DRB3*02:02, HLA-DRB5*01:01",94.51