# Análise de dados TCP-CII

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./T CELL/DENV 3 - T Cell Prediction - Class II.csv')
df

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhciipan_el core,netmhciipan_el score,netmhciipan_el percentile
0,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB3*01:01,7,0.08,FQADSPKRL,0.918785,0.08
1,1,KNGSWKLEKASLIEV,206,220,15,HLA-DRB1*01:01,42,0.10,WKLEKASLI,0.967716,0.10
2,1,YRPGYHTQTAGPWHL,256,270,15,HLA-DQA1*05:01/DQB1*02:01,52,0.20,YHTQTAGPW,0.725588,0.20
3,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB3*02:02,7,0.60,FQADSPKRL,0.605718,0.60
4,1,YGMEIRPISEKEENM,331,345,15,HLA-DQA1*05:01/DQB1*02:01,67,0.72,PISEKEENM,0.569382,0.72
...,...,...,...,...,...,...,...,...,...,...,...
1831,1,WCCRSCTLPPLRYMG,311,325,15,HLA-DRB1*04:05,63,100.00,CRSCTLPPL,0.000071,100.00
1832,1,VITESCGTRGPSLRT,286,300,15,HLA-DRB3*01:01,58,100.00,SCGTRGPSL,0.000068,100.00
1833,1,WCCRSCTLPPLRYMG,311,325,15,HLA-DRB3*01:01,63,100.00,CRSCTLPPL,0.000057,100.00
1834,1,WCCRSCTLPPLRYMG,311,325,15,HLA-DRB1*04:01,63,100.00,RSCTLPPLR,0.000053,100.00
1835,1,KLIHEWCCRSCTLPP,306,320,15,HLA-DRB3*02:02,62,100.00,IHEWCCRSC,0.000027,100.00

## Selecionando Epítopos com median binding percentile menor que 5.

In [3]:
df_mbp_m5 = df[df['median binding percentile'] < 5].copy()
df_mbp_m5

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhciipan_el core,netmhciipan_el score,netmhciipan_el percentile
0,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB3*01:01,7,0.08,FQADSPKRL,0.918785,0.08
1,1,KNGSWKLEKASLIEV,206,220,15,HLA-DRB1*01:01,42,0.10,WKLEKASLI,0.967716,0.10
2,1,YRPGYHTQTAGPWHL,256,270,15,HLA-DQA1*05:01/DQB1*02:01,52,0.20,YHTQTAGPW,0.725588,0.20
3,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB3*02:02,7,0.60,FQADSPKRL,0.605718,0.60
4,1,YGMEIRPISEKEENM,331,345,15,HLA-DQA1*05:01/DQB1*02:01,67,0.72,PISEKEENM,0.569382,0.72
5,1,ADSPKRLATAIAGAW,36,50,15,HLA-DPA1*02:01/DPB1*14:01,8,0.85,RLATAIAGA,0.203444,0.85
6,1,YRPGYHTQTAGPWHL,256,270,15,HLA-DQA1*03:01/DQB1*03:02,52,0.91,YHTQTAGPW,0.022770,0.91
7,1,ERAVHADMGYWIESQ,191,205,15,HLA-DRB3*01:01,39,0.99,VHADMGYWI,0.475558,0.99
8,1,IANELNYILWENNIK,71,85,15,HLA-DPA1*01:03/DPB1*04:01,15,1.10,LNYILWENN,0.270032,1.10
9,1,GVFTTNIWLKLREVY,161,175,15,HLA-DPA1*01:03/DPB1*04:01,33,1.10,FTTNIWLKL,0.240005,1.10
10,1,IANELNYILWENNIK,71,85,15,HLA-DPA1*02:01/DPB1*01:01,15,1.10,LNYILWENN,0.178656,1.10
11,1,IANELNYILWENNIK,71,85,15,HLA-DPA1*01:03/DPB1*02:01,15,1.20,LNYILWENN,0.482008,1.20
12,1,KNGSWKLEKASLIEV,206,220,15,HLA-DRB1*07:01,42,1.30,WKLEKASLI,0.655623,1.30
13,1,KNGSWKLEKASLIEV,206,220,15,HLA-DRB3*02:02,42,1.30,WKLEKASLI,0.401563,1.30
14,1,IANELNYILWENNIK,71,85,15,HLA-DPA1*02:01/DPB1*05:01,15,1.30,LNYILWENN,0.123708,1.30
15,1,IANELNYILWENNIK,71,85,15,HLA-DPA1*03:01/DPB1*04:02,15,1.40,LNYILWENN,0.260275,1.40
16,1,LKYSWKTWGKAKIVT,111,125,15,HLA-DPA1*01:03/DPB1*02:01,23,1.50,YSWKTWGKA,0.417168,1.50
17,1,SSFIIDGPNTPECPS,131,145,15,HLA-DRB3*01:01,27,1.60,FIIDGPNTP,0.349678,1.60
18,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB1*01:01,7,1.70,FQADSPKRL,0.703365,1.70
19,1,ENNIKLTVVVGDTLG,81,95,15,HLA-DRB1*04:05,17,1.70,IKLTVVVGD,0.644253,1.70
20,1,GVFTTNIWLKLREVY,161,175,15,HLA-DPA1*01:03/DPB1*02:01,33,1.70,FTTNIWLKL,0.385363,1.70
21,1,PSLRTTTVSGKLIHE,296,310,15,HLA-DPA1*02:01/DPB1*14:01,60,1.70,RTTTVSGKL,0.144078,1.70
22,1,AKIVTAETQNSSFII,121,135,15,HLA-DRB1*04:01,25,1.80,IVTAETQNS,0.635382,1.80
23,1,GSGIFVTNEVHTWTE,16,30,15,HLA-DRB3*02:02,4,1.80,FVTNEVHTW,0.307360,1.80
24,1,LKYSWKTWGKAKIVT,111,125,15,HLA-DRB1*13:02,23,1.90,WKTWGKAKI,0.502802,1.90
25,1,QYKFQADSPKRLATA,31,45,15,HLA-DPA1*02:01/DPB1*01:01,7,1.90,FQADSPKRL,0.135623,1.90
26,1,KNGSWKLEKASLIEV,206,220,15,HLA-DRB3*01:01,42,2.00,WKLEKASLI,0.288691,2.00
27,1,QYKFQADSPKRLATA,31,45,15,HLA-DPA1*03:01/DPB1*04:02,7,2.00,FQADSPKRL,0.217035,2.00
28,1,GVFTTNIWLKLREVY,161,175,15,HLA-DPA1*03:01/DPB1*04:02,33,2.00,FTTNIWLKL,0.216137,2.00
29,1,GVFTTNIWLKLREVY,161,175,15,HLA-DPA1*02:01/DPB1*01:01,33,2.10,FTTNIWLKL,0.129992,2.10
30,1,QYKFQADSPKRLATA,31,45,15,HLA-DPA1*02:01/DPB1*05:01,7,2.10,FQADSPKRL,0.105522,2.10
31,1,KNGSWKLEKASLIEV,206,220,15,HLA-DRB5*01:01,42,2.30,WKLEKASLI,0.340065,2.30
32,1,DMGCVINWKGKELKC,1,15,15,HLA-DRB1*15:01,1,2.40,VINWKGKEL,0.473601,2.40
33,1,YRPGYHTQTAGPWHL,256,270,15,HLA-DQA1*04:01/DQB1*04:02,52,2.50,YHTQTAGPW,0.178320,2.50
34,1,ASRAWNVWEVEDYGF,146,160,15,HLA-DQA1*01:01/DQB1*05:01,30,2.50,WNVWEVEDY,0.020071,2.50
35,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB1*03:01,7,2.70,FQADSPKRL,0.484358,2.70
36,1,GSGIFVTNEVHTWTE,16,30,15,HLA-DQA1*05:01/DQB1*02:01,4,2.80,FVTNEVHTW,0.364292,2.80
37,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB5*01:01,7,2.90,FQADSPKRL,0.311126,2.90
38,1,YRPGYHTQTAGPWHL,256,270,15,HLA-DQA1*05:01/DQB1*03:01,52,3.00,YHTQTAGPW,0.434450,3.00
39,1,AETQNSSFIIDGPNT,126,140,15,HLA-DQA1*01:02/DQB1*06:02,26,3.10,QNSSFIIDG,0.367283,3.10
40,1,HTWTEQYKFQADSPK,26,40,15,HLA-DRB1*11:01,6,3.40,WTEQYKFQA,0.504343,3.40
41,1,AKIVTAETQNSSFII,121,135,15,HLA-DRB4*01:01,25,3.40,IVTAETQNS,0.210105,3.40
42,1,GSGIFVTNEVHTWTE,16,30,15,HLA-DRB3*01:01,4,3.40,FVTNEVHTW,0.169315,3.40
43,1,QYKFQADSPKRLATA,31,45,15,HLA-DPA1*02:01/DPB1*14:01,7,3.50,FQADSPKRL,0.098275,3.50
44,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB1*13:02,7,3.60,FQADSPKRL,0.383494,3.60
45,1,HRLMSAAVKDERAVH,181,195,15,HLA-DQA1*01:02/DQB1*06:02,37,3.60,SAAVKDERA,0.337674,3.60
46,1,VLEQGKRTLTPQPME,96,110,15,HLA-DPA1*02:01/DPB1*14:01,20,3.70,KRTLTPQPM,0.095819,3.70
47,1,AKIVTAETQNSSFII,121,135,15,HLA-DQA1*05:01/DQB1*03:01,25,3.90,IVTAETQNS,0.370648,3.90
48,1,KTWGKAKIVTAETQN,116,130,15,HLA-DQA1*05:01/DQB1*03:01,24,4.10,WGKAKIVTA,0.360048,4.10
49,1,QYKFQADSPKRLATA,31,45,15,HLA-DPA1*01:03/DPB1*04:01,7,4.20,FQADSPKRL,0.067607,4.20
50,1,YGMEIRPISEKEENM,331,345,15,HLA-DQA1*03:01/DQB1*03:02,67,4.20,IRPISEKEE,0.011152,4.20
51,1,QYKFQADSPKRLATA,31,45,15,HLA-DRB1*07:01,7,4.30,FQADSPKRL,0.359136,4.30
52,1,ERAVHADMGYWIESQ,191,205,15,HLA-DRB1*03:01,39,4.50,VHADMGYWI,0.324145,4.50
53,1,KNGSWKLEKASLIEV,206,220,15,HLA-DPA1*03:01/DPB1*04:02,42,4.50,WKLEKASLI,0.139776,4.50
54,1,KNGSWKLEKASLIEV,206,220,15,HLA-DRB1*09:01,42,4.60,WKLEKASLI,0.419012,4.60
55,1,HRLMSAAVKDERAVH,181,195,15,HLA-DRB1*03:01,37,4.70,MSAAVKDER,0.315477,4.70
56,1,VTNEVHTWTEQYKFQ,21,35,15,HLA-DQA1*04:01/DQB1*04:02,5,4.80,VHTWTEQYK,0.140050,4.80
57,1,AKIVTAETQNSSFII,121,135,15,HLA-DQA1*01:02/DQB1*06:02,25,4.90,IVTAETQNS,0.275224,4.90
58,1,KNGSWKLEKASLIEV,206,220,15,HLA-DPA1*02:01/DPB1*14:01,42,4.90,WKLEKASLI,0.080230,4.90

## Agrupando por pepitideos e agregando colunas pertinentes.

In [4]:
epitopos_repetidos = (
    df_mbp_m5
    .groupby('peptide', as_index=False)
    .agg(
        start=("start", "first"),
        end=("end", "first"),
        qte_de_alelos=("allele", "nunique"),
        median_binding_percentile=(
            "median binding percentile",
            "median"
        ),
        alelos=(
            "allele",
            lambda x: ", ".join(sorted(x.unique()))
        )
    ))

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,ADSPKRLATAIAGAW,36,50,1,0.850,HLA-DPA1*02:01/DPB1*14:01
1,AETQNSSFIIDGPNT,126,140,1,3.100,HLA-DQA1*01:02/DQB1*06:02
2,AKIVTAETQNSSFII,121,135,4,3.650,"HLA-DQA1*01:02/DQB1*06:02, HLA-DQA1*05:01/DQB1..."
3,ASRAWNVWEVEDYGF,146,160,1,2.500,HLA-DQA1*01:01/DQB1*05:01
4,DMGCVINWKGKELKC,1,15,1,2.400,HLA-DRB1*15:01
5,ENNIKLTVVVGDTLG,81,95,1,1.700,HLA-DRB1*04:05
6,ERAVHADMGYWIESQ,191,205,2,2.745,"HLA-DRB1*03:01, HLA-DRB3*01:01"
7,GSGIFVTNEVHTWTE,16,30,3,2.800,"HLA-DQA1*05:01/DQB1*02:01, HLA-DRB3*01:01, HLA..."
8,GVFTTNIWLKLREVY,161,175,4,1.850,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
9,HRLMSAAVKDERAVH,181,195,2,4.150,"HLA-DQA1*01:02/DQB1*06:02, HLA-DRB1*03:01"
10,HTWTEQYKFQADSPK,26,40,1,3.400,HLA-DRB1*11:01
11,IANELNYILWENNIK,71,85,5,1.200,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
12,KNGSWKLEKASLIEV,206,220,8,2.150,"HLA-DPA1*02:01/DPB1*14:01, HLA-DPA1*03:01/DPB1..."
13,KTWGKAKIVTAETQN,116,130,1,4.100,HLA-DQA1*05:01/DQB1*03:01
14,LKYSWKTWGKAKIVT,111,125,2,1.700,"HLA-DPA1*01:03/DPB1*02:01, HLA-DRB1*13:02"
15,PSLRTTTVSGKLIHE,296,310,1,1.700,HLA-DPA1*02:01/DPB1*14:01
16,QYKFQADSPKRLATA,31,45,12,2.400,"HLA-DPA1*01:03/DPB1*04:01, HLA-DPA1*02:01/DPB1..."
17,SSFIIDGPNTPECPS,131,145,1,1.600,HLA-DRB3*01:01
18,VLEQGKRTLTPQPME,96,110,1,3.700,HLA-DPA1*02:01/DPB1*14:01
19,VTNEVHTWTEQYKFQ,21,35,1,4.800,HLA-DQA1*04:01/DQB1*04:02
20,YGMEIRPISEKEENM,331,345,2,2.460,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
21,YRPGYHTQTAGPWHL,256,270,4,1.705,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*04:01/DQB1..."

# Filtragem por epítopos que presentes em mais de 2 alelos.

In [5]:
epitopos_repetidos = epitopos_repetidos[
    epitopos_repetidos["qte_de_alelos"] >= 2
].reset_index(drop=True)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,AKIVTAETQNSSFII,121,135,4,3.650,"HLA-DQA1*01:02/DQB1*06:02, HLA-DQA1*05:01/DQB1..."
1,ERAVHADMGYWIESQ,191,205,2,2.745,"HLA-DRB1*03:01, HLA-DRB3*01:01"
2,GSGIFVTNEVHTWTE,16,30,3,2.800,"HLA-DQA1*05:01/DQB1*02:01, HLA-DRB3*01:01, HLA..."
3,GVFTTNIWLKLREVY,161,175,4,1.850,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
4,HRLMSAAVKDERAVH,181,195,2,4.150,"HLA-DQA1*01:02/DQB1*06:02, HLA-DRB1*03:01"
5,IANELNYILWENNIK,71,85,5,1.200,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
6,KNGSWKLEKASLIEV,206,220,8,2.150,"HLA-DPA1*02:01/DPB1*14:01, HLA-DPA1*03:01/DPB1..."
7,LKYSWKTWGKAKIVT,111,125,2,1.700,"HLA-DPA1*01:03/DPB1*02:01, HLA-DRB1*13:02"
8,QYKFQADSPKRLATA,31,45,12,2.400,"HLA-DPA1*01:03/DPB1*04:01, HLA-DPA1*02:01/DPB1..."
9,YGMEIRPISEKEENM,331,345,2,2.460,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
10,YRPGYHTQTAGPWHL,256,270,4,1.705,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*04:01/DQB1..."

In [6]:
epitopos_repetidos = (
    epitopos_repetidos
    .sort_values(
        ["median_binding_percentile", "qte_de_alelos"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,IANELNYILWENNIK,71,85,5,1.200,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
1,LKYSWKTWGKAKIVT,111,125,2,1.700,"HLA-DPA1*01:03/DPB1*02:01, HLA-DRB1*13:02"
2,YRPGYHTQTAGPWHL,256,270,4,1.705,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*04:01/DQB1..."
3,GVFTTNIWLKLREVY,161,175,4,1.850,"HLA-DPA1*01:03/DPB1*02:01, HLA-DPA1*01:03/DPB1..."
4,KNGSWKLEKASLIEV,206,220,8,2.150,"HLA-DPA1*02:01/DPB1*14:01, HLA-DPA1*03:01/DPB1..."
5,QYKFQADSPKRLATA,31,45,12,2.400,"HLA-DPA1*01:03/DPB1*04:01, HLA-DPA1*02:01/DPB1..."
6,YGMEIRPISEKEENM,331,345,2,2.460,"HLA-DQA1*03:01/DQB1*03:02, HLA-DQA1*05:01/DQB1..."
7,ERAVHADMGYWIESQ,191,205,2,2.745,"HLA-DRB1*03:01, HLA-DRB3*01:01"
8,GSGIFVTNEVHTWTE,16,30,3,2.800,"HLA-DQA1*05:01/DQB1*02:01, HLA-DRB3*01:01, HLA..."
9,AKIVTAETQNSSFII,121,135,4,3.650,"HLA-DQA1*01:02/DQB1*06:02, HLA-DQA1*05:01/DQB1..."
10,HRLMSAAVKDERAVH,181,195,2,4.150,"HLA-DQA1*01:02/DQB1*06:02, HLA-DRB1*03:01"

## Separando epítopos e criando arquivo FASTA para IEDB analysis resource

In [7]:
pepitides = epitopos_repetidos.peptide

with open("./peptideos.fasta", "w") as f:
    for i, peptide in enumerate(pepitides, start=1):
        f.write(f">NP {i}\n")
        f.write(f"{peptide}\n")
        
pepitides

0     IANELNYILWENNIK
1     LKYSWKTWGKAKIVT
2     YRPGYHTQTAGPWHL
3     GVFTTNIWLKLREVY
4     KNGSWKLEKASLIEV
5     QYKFQADSPKRLATA
6     YGMEIRPISEKEENM
7     ERAVHADMGYWIESQ
8     GSGIFVTNEVHTWTE
9     AKIVTAETQNSSFII
10    HRLMSAAVKDERAVH
Name: peptide, dtype: str

### Seqkit remove sequências proteicas contendo gaps e *.

In [10]:
!seqkit grep -s -v -r -p '[-*X]' 'denv3_NS1_proteinas.fasta' > DENV3_seq_filter_all.fasta

### Resultado IEDB analysis resource

In [11]:
conservacy_result = pd.read_csv('./ConservancyResult.csv')
conservacy_result

,Epitope #,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,View details
0,1,NP 1,IANELNYILWENNIK,15,89.81% (573/638),66.67%,100.00%,NaN
1,2,NP 2,LKYSWKTWGKAKIVT,15,96.55% (616/638),73.33%,100.00%,NaN
2,3,NP 3,YRPGYHTQTAGPWHL,15,57.05% (364/638),86.67%,100.00%,NaN
3,4,NP 4,GVFTTNIWLKLREVY,15,71.32% (455/638),80.00%,100.00%,NaN
4,5,NP 5,KNGSWKLEKASLIEV,15,81.03% (517/638),66.67%,100.00%,NaN
5,6,NP 6,QYKFQADSPKRLATA,15,94.83% (605/638),80.00%,100.00%,NaN
6,7,NP 7,YGMEIRPISEKEENM,15,61.13% (390/638),80.00%,100.00%,NaN
7,8,NP 8,ERAVHADMGYWIESQ,15,99.06% (632/638),80.00%,100.00%,NaN
8,9,NP 9,GSGIFVTNEVHTWTE,15,86.05% (549/638),93.33%,100.00%,NaN
9,10,NP 10,AKIVTAETQNSSFII,15,94.98% (606/638),60.00%,100.00%,NaN
10,11,NP 11,HRLMSAAVKDERAVH,15,80.88% (516/638),80.00%,100.00%,NaN

### Gerando a coluna percent_match para filtrar os epitopos com percentagem de match maior que 50%

In [12]:
col = "Percent of protein sequence matches at identity <= 100%"

conservacy_result["percent_match"] = (
    conservacy_result[col]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
    .astype(float)
)

conservacy_result

,Epitope #,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,View details,percent_match
0,1,NP 1,IANELNYILWENNIK,15,89.81% (573/638),66.67%,100.00%,NaN,89.81
1,2,NP 2,LKYSWKTWGKAKIVT,15,96.55% (616/638),73.33%,100.00%,NaN,96.55
2,3,NP 3,YRPGYHTQTAGPWHL,15,57.05% (364/638),86.67%,100.00%,NaN,57.05
3,4,NP 4,GVFTTNIWLKLREVY,15,71.32% (455/638),80.00%,100.00%,NaN,71.32
4,5,NP 5,KNGSWKLEKASLIEV,15,81.03% (517/638),66.67%,100.00%,NaN,81.03
5,6,NP 6,QYKFQADSPKRLATA,15,94.83% (605/638),80.00%,100.00%,NaN,94.83
6,7,NP 7,YGMEIRPISEKEENM,15,61.13% (390/638),80.00%,100.00%,NaN,61.13
7,8,NP 8,ERAVHADMGYWIESQ,15,99.06% (632/638),80.00%,100.00%,NaN,99.06
8,9,NP 9,GSGIFVTNEVHTWTE,15,86.05% (549/638),93.33%,100.00%,NaN,86.05
9,10,NP 10,AKIVTAETQNSSFII,15,94.98% (606/638),60.00%,100.00%,NaN,94.98
10,11,NP 11,HRLMSAAVKDERAVH,15,80.88% (516/638),80.00%,100.00%,NaN,80.88

### Sort por percent_match e filtragem por percent_match >= 95.00

In [13]:
conservacy_result_filtered = (
    conservacy_result[conservacy_result["percent_match"] >= 95.0]
    .sort_values(
            by="percent_match", 
            ascending=False
        )
    )

conservacy_result_filtered

,Epitope #,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,View details,percent_match
7,8,NP 8,ERAVHADMGYWIESQ,15,99.06% (632/638),80.00%,100.00%,NaN,99.06
1,2,NP 2,LKYSWKTWGKAKIVT,15,96.55% (616/638),73.33%,100.00%,NaN,96.55