# Análise de dados TCP-CII

### Importação dos parâmetros universais

In [1]:
import importlib.util
from pathlib import Path

path = Path("../../../parametros/config.py").resolve()

spec = importlib.util.spec_from_file_location("parametros", path)
parametros = importlib.util.module_from_spec(spec)
spec.loader.exec_module(parametros)

In [2]:
# Parâmetros importados do arquivo config.py
print(
    "Filtrar por quantidade de alelos TCC1:.........................",
    parametros.filtarar_por_qte_de_alelos_tcc1,
)
print(
    "Parâmetro de filtragem median binding percentile TCC1:.........",
    parametros.parametro_de_filtragem_mbp_tcc1,
)
print(
    "Percentual de match mínimo TCC1:...............................",
    parametros.percent_match_minimo_tcc1,
)

Filtrar por quantidade de alelos TCC1:......................... 10
Parâmetro de filtragem median binding percentile TCC1:......... 5
Percentual de match mínimo TCC1:............................... 95.0

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('./T CELL/DENV 1 - T Cell Prediction - Class I.csv')
df

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTGKTIHEW,303,311,9,HLA-B*57:01,303,0.01,VTGKTIHEW,VTGKTIHEW,0.997406,0.01
1,1,VTGKTIHEW,303,311,9,HLA-B*58:01,303,0.01,VTGKTIHEW,VTGKTIHEW,0.996622,0.01
2,1,SEMIIPKIY,239,247,9,HLA-B*44:03,239,0.01,SEMIIPKIY,SEMIIPKIY,0.996239,0.01
3,1,SEMIIPKIY,239,247,9,HLA-B*44:02,239,0.01,SEMIIPKIY,SEMIIPKIY,0.992169,0.01
4,1,LSAAIGKAW,42,50,9,HLA-B*57:01,42,0.01,LSAAIGKAW,LSAAIGKAW,0.989554,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
36985,1,PVKEKEENLVKS,337,348,12,HLA-B*53:01,1366,100.00,PVEENLVKS,PVKEKEENLVKS,0.000000,100.00
36986,1,EKEENLVKSMVS,340,351,12,HLA-A*11:01,1369,100.00,ENLVKSMVS,EKEENLVKSMVS,0.000000,100.00
36987,1,EKEENLVKSMVS,340,351,12,HLA-A*24:02,1369,100.00,EKEENKSMV,EKEENLVKSMV,0.000000,100.00
36988,1,EKEENLVKSMVS,340,351,12,HLA-A*32:01,1369,100.00,ENLVKSMVS,EKEENLVKSMVS,0.000000,100.00
36989,1,EKEENLVKSMVS,340,351,12,HLA-A*68:01,1369,100.00,EKEENLVKS,EKEENLVKSMVS,0.000000,100.00

## Selecionando Epítopos por median binding percentile.

In [5]:
mbp_minimo = parametros.parametro_de_filtragem_mbp_tcc1

In [6]:
df_mbp_m5 = df[df['median binding percentile'] < mbp_minimo].copy()
print("Filtrando por median binding percentile < ", mbp_minimo)
df_mbp_m5

Filtrando por median binding percentile <  5

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTGKTIHEW,303,311,9,HLA-B*57:01,303,0.01,VTGKTIHEW,VTGKTIHEW,0.997406,0.01
1,1,VTGKTIHEW,303,311,9,HLA-B*58:01,303,0.01,VTGKTIHEW,VTGKTIHEW,0.996622,0.01
2,1,SEMIIPKIY,239,247,9,HLA-B*44:03,239,0.01,SEMIIPKIY,SEMIIPKIY,0.996239,0.01
3,1,SEMIIPKIY,239,247,9,HLA-B*44:02,239,0.01,SEMIIPKIY,SEMIIPKIY,0.992169,0.01
4,1,LSAAIGKAW,42,50,9,HLA-B*57:01,42,0.01,LSAAIGKAW,LSAAIGKAW,0.989554,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2496,1,LSAAIGKAW,42,50,9,HLA-A*24:02,42,4.90,LSAAIGKAW,LSAAIGKAW,0.003380,4.90
2497,1,TCIWPKSHTLWS,222,233,12,HLA-A*24:02,1251,4.90,TWPKSHTLW,TCIWPKSHTLW,0.003356,4.90
2498,1,SWKSWGKAKII,114,124,11,HLA-A*24:02,801,4.90,SWWGKAKII,SWKSWGKAKII,0.003267,4.90
2499,1,SEKNETWKLARA,204,215,12,HLA-B*44:03,1233,4.90,SEKNETWKA,SEKNETWKLARA,0.003159,4.90
2500,1,RFKGEDGCW,322,330,9,HLA-B*44:03,322,4.90,RFKGEDGCW,RFKGEDGCW,0.003103,4.90

## Agrupando por pepitideos e agregando colunas pertinentes

In [7]:
epitopos_repetidos = (
    df_mbp_m5
    .groupby('peptide', as_index=False)
    .agg(
        start=("start", "first"),
        end=("end", "first"),
        qte_de_alelos=("allele", "nunique"),
        median_binding_percentile=(
            "median binding percentile",
            "median"
        ),
        alelos=(
            "allele",
            lambda x: ", ".join(sorted(x.unique()))
        )
    )
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,AAIGKAWEEGV,44,54,3,2.90,"HLA-A*02:01, HLA-A*02:06, HLA-A*68:02"
1,AAIKDSKAV,186,194,7,2.60,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*6..."
2,AAIKDSKAVH,186,195,2,3.50,"HLA-A*30:02, HLA-B*15:01"
3,ADMGYWIESEK,196,206,2,4.15,"HLA-A*03:01, HLA-A*11:01"
4,ADSPKRLSA,36,44,3,3.20,"HLA-B*08:01, HLA-B*40:01, HLA-B*44:02"
...,...,...,...,...,...,...
597,YTQVCDHRL,175,183,8,2.95,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
598,YTQVCDHRLM,175,184,4,3.45,"HLA-A*01:01, HLA-B*15:01, HLA-B*57:01, HLA-B*5..."
599,YTQVCDHRLMSA,175,186,1,2.50,HLA-A*01:01
600,YWIESEKNETW,200,210,10,0.80,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."
601,YWIESEKNETWK,200,211,4,2.55,"HLA-A*23:01, HLA-A*24:02, HLA-B*44:02, HLA-B*4..."

## Filtragem por qte_de_alelos

In [8]:
# Filtro do número de alelos
epitopos_repetidos = epitopos_repetidos[
    epitopos_repetidos["qte_de_alelos"] >= parametros.filtarar_por_qte_de_alelos_tcc1
].reset_index(drop=True)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,ATRLENIMW,60,68,13,3.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
1,AVHADMGYW,193,201,10,1.645,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
2,CIWPKSHTL,223,231,20,1.600,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
3,CTLPPLRFK,316,324,12,1.850,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
4,ECPDNQRAW,142,150,11,1.900,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
5,ESEMIIPKIY,238,247,10,2.550,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-B*3..."
6,ETWKLARASF,208,217,13,2.800,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
7,EVHTWTEQY,24,32,16,1.500,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
8,EVHTWTEQYKF,24,34,10,3.250,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
9,FQADSPKRL,34,42,18,2.450,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
10,FTQTAGPWHL,261,270,10,2.850,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
11,FTTNIWLKL,163,171,16,1.650,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
12,FVTNEVHTW,20,28,17,1.200,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
13,GADVQNTTF,125,133,15,3.600,"HLA-A*01:01, HLA-A*02:06, HLA-A*26:01, HLA-A*3..."
14,HILLENDMKF,77,86,11,2.500,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
15,HTWTEQYKF,26,34,21,1.500,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
16,IESEKNETW,202,210,12,1.010,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
17,IGADVQNTTF,124,133,11,1.900,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
18,ILLENDMKF,78,86,17,1.200,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
19,IRPQPMEHKY,104,113,14,2.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
20,IRPQPMEHKYSW,104,115,10,2.200,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
21,ISNELNHIL,71,79,19,2.600,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
22,IWPKSHTLW,224,232,10,0.960,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
23,KAVHADMGY,192,200,11,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
24,KFQADSPKRL,33,42,10,2.800,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
25,KIYGGPISQ,245,253,10,2.500,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
26,KIYGGPISQHNY,245,256,12,1.500,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
27,KLRDSYTQV,170,178,12,1.400,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
28,KTCIWPKSHTL,221,231,15,1.500,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
29,LSAAIGKAW,42,50,12,2.350,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
30,MIRPQPMEH,103,111,15,2.000,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
31,MIRPQPMEHKY,103,113,13,1.800,"HLA-A*01:01, HLA-A*03:01, HLA-A*26:01, HLA-A*3..."
32,MWKQISNEL,67,75,12,2.550,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:01, HLA-A*3..."
33,NEVHTWTEQY,23,32,10,1.600,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6..."
34,PQPMEHKYSW,106,115,10,1.900,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
35,QPMEHKYSW,107,115,16,0.545,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
36,QTAGPWHLGK,263,272,10,1.850,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
37,QTAGPWHLGKL,263,273,12,3.000,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
38,RPQPMEHKY,105,113,19,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
39,RPQPMEHKYSW,105,115,12,1.350,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
40,RSCTLPPLR,314,322,10,1.950,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
41,RSCTLPPLRFK,314,324,10,2.300,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
42,SCTLPPLRF,315,323,13,3.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
43,SEKNETWKL,204,212,11,3.200,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
44,SQHNYRPGY,252,260,14,1.285,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
45,TCIWPKSHTL,222,231,14,2.450,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
46,TQTAGPWHL,262,270,14,1.850,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
47,TVTGKTIHEW,302,311,11,2.500,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
48,TWKLARASF,209,217,11,3.400,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
49,VEDYGFGIF,155,163,10,3.900,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
50,VTGKTIHEW,303,311,14,1.350,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
51,YWIESEKNETW,200,210,10,0.800,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."

## Sorting por median_biding_percentile

In [9]:
epitopos_repetidos = (
    epitopos_repetidos
    .sort_values(
        ["median_binding_percentile", "qte_de_alelos"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,QPMEHKYSW,107,115,16,0.545,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
1,YWIESEKNETW,200,210,10,0.800,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."
2,IWPKSHTLW,224,232,10,0.960,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
3,IESEKNETW,202,210,12,1.010,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
4,FVTNEVHTW,20,28,17,1.200,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
5,ILLENDMKF,78,86,17,1.200,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
6,KAVHADMGY,192,200,11,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
7,SQHNYRPGY,252,260,14,1.285,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
8,VTGKTIHEW,303,311,14,1.350,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
9,RPQPMEHKYSW,105,115,12,1.350,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
10,RPQPMEHKY,105,113,19,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
11,KLRDSYTQV,170,178,12,1.400,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
12,HTWTEQYKF,26,34,21,1.500,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
13,EVHTWTEQY,24,32,16,1.500,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
14,KTCIWPKSHTL,221,231,15,1.500,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
15,KIYGGPISQHNY,245,256,12,1.500,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
16,CIWPKSHTL,223,231,20,1.600,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
17,NEVHTWTEQY,23,32,10,1.600,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6..."
18,AVHADMGYW,193,201,10,1.645,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
19,FTTNIWLKL,163,171,16,1.650,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
20,MIRPQPMEHKY,103,113,13,1.800,"HLA-A*01:01, HLA-A*03:01, HLA-A*26:01, HLA-A*3..."
21,QTAGPWHLGK,263,272,10,1.850,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
22,TQTAGPWHL,262,270,14,1.850,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
23,CTLPPLRFK,316,324,12,1.850,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
24,ECPDNQRAW,142,150,11,1.900,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
25,IGADVQNTTF,124,133,11,1.900,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
26,PQPMEHKYSW,106,115,10,1.900,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
27,RSCTLPPLR,314,322,10,1.950,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
28,MIRPQPMEH,103,111,15,2.000,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
29,IRPQPMEHKYSW,104,115,10,2.200,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
30,RSCTLPPLRFK,314,324,10,2.300,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
31,LSAAIGKAW,42,50,12,2.350,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
32,FQADSPKRL,34,42,18,2.450,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
33,TCIWPKSHTL,222,231,14,2.450,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
34,HILLENDMKF,77,86,11,2.500,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
35,TVTGKTIHEW,302,311,11,2.500,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
36,KIYGGPISQ,245,253,10,2.500,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
37,MWKQISNEL,67,75,12,2.550,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:01, HLA-A*3..."
38,ESEMIIPKIY,238,247,10,2.550,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-B*3..."
39,ISNELNHIL,71,79,19,2.600,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
40,IRPQPMEHKY,104,113,14,2.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
41,ETWKLARASF,208,217,13,2.800,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
42,KFQADSPKRL,33,42,10,2.800,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
43,FTQTAGPWHL,261,270,10,2.850,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
44,QTAGPWHLGKL,263,273,12,3.000,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
45,SCTLPPLRF,315,323,13,3.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
46,SEKNETWKL,204,212,11,3.200,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
47,EVHTWTEQYKF,24,34,10,3.250,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
48,ATRLENIMW,60,68,13,3.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
49,TWKLARASF,209,217,11,3.400,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
50,GADVQNTTF,125,133,15,3.600,"HLA-A*01:01, HLA-A*02:06, HLA-A*26:01, HLA-A*3..."
51,VEDYGFGIF,155,163,10,3.900,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

## Separando epítopos e criando arquivo FASTA para IEDB analysis resource

In [10]:
pepitides = epitopos_repetidos.peptide

with open("./peptideos_tcell_1.fasta", "w") as f:
    for i, peptide in enumerate(pepitides, start=1):
        f.write(f">NP {i}\n")
        f.write(f"{peptide}\n")
        
pepitides

0        QPMEHKYSW
1      YWIESEKNETW
2        IWPKSHTLW
3        IESEKNETW
4        FVTNEVHTW
5        ILLENDMKF
6        KAVHADMGY
7        SQHNYRPGY
8        VTGKTIHEW
9      RPQPMEHKYSW
10       RPQPMEHKY
11       KLRDSYTQV
12       HTWTEQYKF
13       EVHTWTEQY
14     KTCIWPKSHTL
15    KIYGGPISQHNY
16       CIWPKSHTL
17      NEVHTWTEQY
18       AVHADMGYW
19       FTTNIWLKL
20     MIRPQPMEHKY
21      QTAGPWHLGK
22       TQTAGPWHL
23       CTLPPLRFK
24       ECPDNQRAW
25      IGADVQNTTF
26      PQPMEHKYSW
27       RSCTLPPLR
28       MIRPQPMEH
29    IRPQPMEHKYSW
30     RSCTLPPLRFK
31       LSAAIGKAW
32       FQADSPKRL
33      TCIWPKSHTL
34      HILLENDMKF
35      TVTGKTIHEW
36       KIYGGPISQ
37       MWKQISNEL
38      ESEMIIPKIY
39       ISNELNHIL
40      IRPQPMEHKY
41      ETWKLARASF
42      KFQADSPKRL
43      FTQTAGPWHL
44     QTAGPWHLGKL
45       SCTLPPLRF
46       SEKNETWKL
47     EVHTWTEQYKF
48       ATRLENIMW
49       TWKLARASF
50       GADVQNTTF
51       VEDYGFGIF
Name: peptide, dtype: str

### Seqkit remove sequências proteicas contendo gaps e *.

In [11]:
# !seqkit grep -s -v -r -p '[-*]' './Fastas/denv1_NS1_proteinas.fa' > DENV1_seq_filter_all.fasta

### Resultado IEDB analysis resource

In [12]:
conservacy_result = pd.read_csv('./ConservancyResult_tcell_1.csv')
conservacy_result

,Epitope #,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,View details
0,1,NP 1,HTWTEQYKF,9,99.80% (1013/1015),88.89%,100.00%,NaN
1,2,NP 2,CIWPKSHTL,9,67.68% (687/1015),77.78%,100.00%,NaN
2,3,NP 3,RPQPMEHKY,9,62.96% (639/1015),77.78%,100.00%,NaN
3,4,NP 4,ISNELNHIL,9,95.76% (972/1015),77.78%,100.00%,NaN
4,5,NP 5,FQADSPKRL,9,99.90% (1014/1015),88.89%,100.00%,NaN
5,6,NP 6,FVTNEVHTW,9,99.61% (1011/1015),88.89%,100.00%,NaN
6,7,NP 7,ILLENDMKF,9,88.47% (898/1015),55.56%,100.00%,NaN
7,8,NP 8,QPMEHKYSW,9,63.65% (646/1015),77.78%,100.00%,NaN
8,9,NP 9,EVHTWTEQY,9,99.80% (1013/1015),88.89%,100.00%,NaN
9,10,NP 10,FTTNIWLKL,9,98.03% (995/1015),88.89%,100.00%,NaN
10,11,NP 11,KTCIWPKSHTL,11,67.68% (687/1015),81.82%,100.00%,NaN
11,12,NP 12,MIRPQPMEH,9,63.74% (647/1015),55.56%,100.00%,NaN
12,13,NP 13,GADVQNTTF,9,52.51% (533/1015),44.44%,100.00%,NaN
13,14,NP 14,SQHNYRPGY,9,98.82% (1003/1015),88.89%,100.00%,NaN
14,15,NP 15,VTGKTIHEW,9,0.69% (7/1015),77.78%,100.00%,NaN
15,16,NP 16,TQTAGPWHL,9,97.24% (987/1015),88.89%,100.00%,NaN
16,17,NP 17,TCIWPKSHTL,10,67.68% (687/1015),80.00%,100.00%,NaN
17,18,NP 18,IRPQPMEHKY,10,62.56% (635/1015),70.00%,100.00%,NaN
18,19,NP 19,MIRPQPMEHKY,11,61.77% (627/1015),63.64%,100.00%,NaN
19,20,NP 20,ETWKLARASF,10,89.56% (909/1015),50.00%,100.00%,NaN
20,21,NP 21,SCTLPPLRF,9,96.85% (983/1015),88.89%,100.00%,NaN
21,22,NP 22,ATRLENIMW,9,95.86% (973/1015),55.56%,100.00%,NaN
22,23,NP 23,IESEKNETW,9,98.03% (995/1015),66.67%,100.00%,NaN
23,24,NP 24,RPQPMEHKYSW,11,62.86% (638/1015),81.82%,100.00%,NaN
24,25,NP 25,KLRDSYTQV,9,59.41% (603/1015),66.67%,100.00%,NaN
25,26,NP 26,KIYGGPISQHNY,12,85.12% (864/1015),75.00%,100.00%,NaN
26,27,NP 27,CTLPPLRFK,9,32.71% (332/1015),77.78%,100.00%,NaN
27,28,NP 28,LSAAIGKAW,9,97.04% (985/1015),55.56%,100.00%,NaN
28,29,NP 29,MWKQISNEL,9,96.55% (980/1015),77.78%,100.00%,NaN
29,30,NP 30,QTAGPWHLGKL,11,97.04% (985/1015),90.91%,100.00%,NaN
30,31,NP 31,KAVHADMGY,9,98.42% (999/1015),88.89%,100.00%,NaN
31,32,NP 32,ECPDNQRAW,9,9.56% (97/1015),66.67%,100.00%,NaN
32,33,NP 33,IGADVQNTTF,10,52.32% (531/1015),40.00%,100.00%,NaN
33,34,NP 34,HILLENDMKF,10,86.21% (875/1015),50.00%,100.00%,NaN
34,35,NP 35,TVTGKTIHEW,10,0.69% (7/1015),80.00%,100.00%,NaN
35,36,NP 36,SEKNETWKL,9,98.03% (995/1015),66.67%,100.00%,NaN
36,37,NP 37,TWKLARASF,9,90.25% (916/1015),55.56%,100.00%,NaN
37,38,NP 38,YWIESEKNETW,11,98.03% (995/1015),72.73%,100.00%,NaN
38,39,NP 39,IWPKSHTLW,9,67.68% (687/1015),77.78%,100.00%,NaN
39,40,NP 40,NEVHTWTEQY,10,99.80% (1013/1015),90.00%,100.00%,NaN
40,41,NP 41,AVHADMGYW,9,99.61% (1011/1015),88.89%,100.00%,NaN
41,42,NP 42,QTAGPWHLGK,10,97.04% (985/1015),90.00%,100.00%,NaN
42,43,NP 43,PQPMEHKYSW,10,63.65% (646/1015),80.00%,100.00%,NaN
43,44,NP 44,RSCTLPPLR,9,99.80% (1013/1015),88.89%,100.00%,NaN
44,45,NP 45,IRPQPMEHKYSW,12,62.46% (634/1015),75.00%,100.00%,NaN
45,46,NP 46,RSCTLPPLRFK,11,32.71% (332/1015),81.82%,100.00%,NaN
46,47,NP 47,KIYGGPISQ,9,86.01% (873/1015),66.67%,100.00%,NaN
47,48,NP 48,ESEMIIPKIY,10,83.55% (848/1015),70.00%,100.00%,NaN
48,49,NP 49,KFQADSPKRL,10,99.80% (1013/1015),90.00%,100.00%,NaN
49,50,NP 50,FTQTAGPWHL,10,95.86% (973/1015),90.00%,100.00%,NaN
50,51,NP 51,EVHTWTEQYKF,11,99.70% (1012/1015),90.91%,100.00%,NaN
51,52,NP 52,VEDYGFGIF,9,90.94% (923/1015),88.89%,100.00%,NaN

### Merge da coluna qte_de_alelos ao dataframe conservacy_result

In [13]:
# qte_de_alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "qte_de_alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("View details"))

# alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("Epitope #"))

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos
0,NP 1,HTWTEQYKF,9,99.80% (1013/1015),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
1,NP 2,CIWPKSHTL,9,67.68% (687/1015),77.78%,100.00%,20,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
2,NP 3,RPQPMEHKY,9,62.96% (639/1015),77.78%,100.00%,19,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
3,NP 4,ISNELNHIL,9,95.76% (972/1015),77.78%,100.00%,19,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
4,NP 5,FQADSPKRL,9,99.90% (1014/1015),88.89%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
5,NP 6,FVTNEVHTW,9,99.61% (1011/1015),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
6,NP 7,ILLENDMKF,9,88.47% (898/1015),55.56%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
7,NP 8,QPMEHKYSW,9,63.65% (646/1015),77.78%,100.00%,16,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
8,NP 9,EVHTWTEQY,9,99.80% (1013/1015),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
9,NP 10,FTTNIWLKL,9,98.03% (995/1015),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
10,NP 11,KTCIWPKSHTL,11,67.68% (687/1015),81.82%,100.00%,15,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
11,NP 12,MIRPQPMEH,9,63.74% (647/1015),55.56%,100.00%,15,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
12,NP 13,GADVQNTTF,9,52.51% (533/1015),44.44%,100.00%,15,"HLA-A*01:01, HLA-A*02:06, HLA-A*26:01, HLA-A*3..."
13,NP 14,SQHNYRPGY,9,98.82% (1003/1015),88.89%,100.00%,14,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
14,NP 15,VTGKTIHEW,9,0.69% (7/1015),77.78%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
15,NP 16,TQTAGPWHL,9,97.24% (987/1015),88.89%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
16,NP 17,TCIWPKSHTL,10,67.68% (687/1015),80.00%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
17,NP 18,IRPQPMEHKY,10,62.56% (635/1015),70.00%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
18,NP 19,MIRPQPMEHKY,11,61.77% (627/1015),63.64%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*26:01, HLA-A*3..."
19,NP 20,ETWKLARASF,10,89.56% (909/1015),50.00%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
20,NP 21,SCTLPPLRF,9,96.85% (983/1015),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
21,NP 22,ATRLENIMW,9,95.86% (973/1015),55.56%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
22,NP 23,IESEKNETW,9,98.03% (995/1015),66.67%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
23,NP 24,RPQPMEHKYSW,11,62.86% (638/1015),81.82%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
24,NP 25,KLRDSYTQV,9,59.41% (603/1015),66.67%,100.00%,12,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
25,NP 26,KIYGGPISQHNY,12,85.12% (864/1015),75.00%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
26,NP 27,CTLPPLRFK,9,32.71% (332/1015),77.78%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
27,NP 28,LSAAIGKAW,9,97.04% (985/1015),55.56%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
28,NP 29,MWKQISNEL,9,96.55% (980/1015),77.78%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:01, HLA-A*3..."
29,NP 30,QTAGPWHLGKL,11,97.04% (985/1015),90.91%,100.00%,12,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
30,NP 31,KAVHADMGY,9,98.42% (999/1015),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
31,NP 32,ECPDNQRAW,9,9.56% (97/1015),66.67%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
32,NP 33,IGADVQNTTF,10,52.32% (531/1015),40.00%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
33,NP 34,HILLENDMKF,10,86.21% (875/1015),50.00%,100.00%,11,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
34,NP 35,TVTGKTIHEW,10,0.69% (7/1015),80.00%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
35,NP 36,SEKNETWKL,9,98.03% (995/1015),66.67%,100.00%,11,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
36,NP 37,TWKLARASF,9,90.25% (916/1015),55.56%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
37,NP 38,YWIESEKNETW,11,98.03% (995/1015),72.73%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."
38,NP 39,IWPKSHTLW,9,67.68% (687/1015),77.78%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
39,NP 40,NEVHTWTEQY,10,99.80% (1013/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6..."
40,NP 41,AVHADMGYW,9,99.61% (1011/1015),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
41,NP 42,QTAGPWHLGK,10,97.04% (985/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
42,NP 43,PQPMEHKYSW,10,63.65% (646/1015),80.00%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
43,NP 44,RSCTLPPLR,9,99.80% (1013/1015),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
44,NP 45,IRPQPMEHKYSW,12,62.46% (634/1015),75.00%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
45,NP 46,RSCTLPPLRFK,11,32.71% (332/1015),81.82%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
46,NP 47,KIYGGPISQ,9,86.01% (873/1015),66.67%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
47,NP 48,ESEMIIPKIY,10,83.55% (848/1015),70.00%,100.00%,10,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-B*3..."
48,NP 49,KFQADSPKRL,10,99.80% (1013/1015),90.00%,100.00%,10,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
49,NP 50,FTQTAGPWHL,10,95.86% (973/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
50,NP 51,EVHTWTEQYKF,11,99.70% (1012/1015),90.91%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
51,NP 52,VEDYGFGIF,9,90.94% (923/1015),88.89%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

### Gerando a coluna percent_match para filtrar os epitopos com percentagem de match maior que 50%

In [14]:
col = "Percent of protein sequence matches at identity <= 100%"

conservacy_result["percent_match"] = (
    conservacy_result[col]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
    .astype(float)
)

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos,percent_match
0,NP 1,HTWTEQYKF,9,99.80% (1013/1015),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2...",99.80
1,NP 2,CIWPKSHTL,9,67.68% (687/1015),77.78%,100.00%,20,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",67.68
2,NP 3,RPQPMEHKY,9,62.96% (639/1015),77.78%,100.00%,19,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",62.96
3,NP 4,ISNELNHIL,9,95.76% (972/1015),77.78%,100.00%,19,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",95.76
4,NP 5,FQADSPKRL,9,99.90% (1014/1015),88.89%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",99.90
5,NP 6,FVTNEVHTW,9,99.61% (1011/1015),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2...",99.61
6,NP 7,ILLENDMKF,9,88.47% (898/1015),55.56%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",88.47
7,NP 8,QPMEHKYSW,9,63.65% (646/1015),77.78%,100.00%,16,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",63.65
8,NP 9,EVHTWTEQY,9,99.80% (1013/1015),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.80
9,NP 10,FTTNIWLKL,9,98.03% (995/1015),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",98.03
10,NP 11,KTCIWPKSHTL,11,67.68% (687/1015),81.82%,100.00%,15,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",67.68
11,NP 12,MIRPQPMEH,9,63.74% (647/1015),55.56%,100.00%,15,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",63.74
12,NP 13,GADVQNTTF,9,52.51% (533/1015),44.44%,100.00%,15,"HLA-A*01:01, HLA-A*02:06, HLA-A*26:01, HLA-A*3...",52.51
13,NP 14,SQHNYRPGY,9,98.82% (1003/1015),88.89%,100.00%,14,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",98.82
14,NP 15,VTGKTIHEW,9,0.69% (7/1015),77.78%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",0.69
15,NP 16,TQTAGPWHL,9,97.24% (987/1015),88.89%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",97.24
16,NP 17,TCIWPKSHTL,10,67.68% (687/1015),80.00%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",67.68
17,NP 18,IRPQPMEHKY,10,62.56% (635/1015),70.00%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",62.56
18,NP 19,MIRPQPMEHKY,11,61.77% (627/1015),63.64%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*26:01, HLA-A*3...",61.77
19,NP 20,ETWKLARASF,10,89.56% (909/1015),50.00%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",89.56
20,NP 21,SCTLPPLRF,9,96.85% (983/1015),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",96.85
21,NP 22,ATRLENIMW,9,95.86% (973/1015),55.56%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",95.86
22,NP 23,IESEKNETW,9,98.03% (995/1015),66.67%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",98.03
23,NP 24,RPQPMEHKYSW,11,62.86% (638/1015),81.82%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0...",62.86
24,NP 25,KLRDSYTQV,9,59.41% (603/1015),66.67%,100.00%,12,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0...",59.41
25,NP 26,KIYGGPISQHNY,12,85.12% (864/1015),75.00%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",85.12
26,NP 27,CTLPPLRFK,9,32.71% (332/1015),77.78%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",32.71
27,NP 28,LSAAIGKAW,9,97.04% (985/1015),55.56%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.04
28,NP 29,MWKQISNEL,9,96.55% (980/1015),77.78%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:01, HLA-A*3...",96.55
29,NP 30,QTAGPWHLGKL,11,97.04% (985/1015),90.91%,100.00%,12,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",97.04
30,NP 31,KAVHADMGY,9,98.42% (999/1015),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",98.42
31,NP 32,ECPDNQRAW,9,9.56% (97/1015),66.67%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",9.56
32,NP 33,IGADVQNTTF,10,52.32% (531/1015),40.00%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3...",52.32
33,NP 34,HILLENDMKF,10,86.21% (875/1015),50.00%,100.00%,11,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",86.21
34,NP 35,TVTGKTIHEW,10,0.69% (7/1015),80.00%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",0.69
35,NP 36,SEKNETWKL,9,98.03% (995/1015),66.67%,100.00%,11,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",98.03
36,NP 37,TWKLARASF,9,90.25% (916/1015),55.56%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",90.25
37,NP 38,YWIESEKNETW,11,98.03% (995/1015),72.73%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3...",98.03
38,NP 39,IWPKSHTLW,9,67.68% (687/1015),77.78%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3...",67.68
39,NP 40,NEVHTWTEQY,10,99.80% (1013/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6...",99.80
40,NP 41,AVHADMGYW,9,99.61% (1011/1015),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3...",99.61
41,NP 42,QTAGPWHLGK,10,97.04% (985/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.04
42,NP 43,PQPMEHKYSW,10,63.65% (646/1015),80.00%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0...",63.65
43,NP 44,RSCTLPPLR,9,99.80% (1013/1015),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",99.80
44,NP 45,IRPQPMEHKYSW,12,62.46% (634/1015),75.00%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0...",62.46
45,NP 46,RSCTLPPLRFK,11,32.71% (332/1015),81.82%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",32.71
46,NP 47,KIYGGPISQ,9,86.01% (873/1015),66.67%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0...",86.01
47,NP 48,ESEMIIPKIY,10,83.55% (848/1015),70.00%,100.00%,10,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-B*3...",83.55
48,NP 49,KFQADSPKRL,10,99.80% (1013/1015),90.00%,100.00%,10,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",99.80
49,NP 50,FTQTAGPWHL,10,95.86% (973/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",95.86
50,NP 51,EVHTWTEQYKF,11,99.70% (1012/1015),90.91%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.70
51,NP 52,VEDYGFGIF,9,90.94% (923/1015),88.89%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",90.94

### Sort e filtragem por percent_match e presença em alelos

In [15]:
# Filtro do Percent match
conservacy_result_filtered = (
    conservacy_result[conservacy_result["percent_match"] >= parametros.percent_match_minimo_tcc1]
    .sort_values(
            by="percent_match", 
            ascending=False
        )
    ).reset_index(drop=True)

conservacy_result_filtered

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos,percent_match
0,NP 5,FQADSPKRL,9,99.90% (1014/1015),88.89%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",99.90
1,NP 1,HTWTEQYKF,9,99.80% (1013/1015),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2...",99.80
2,NP 9,EVHTWTEQY,9,99.80% (1013/1015),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.80
3,NP 44,RSCTLPPLR,9,99.80% (1013/1015),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",99.80
4,NP 49,KFQADSPKRL,10,99.80% (1013/1015),90.00%,100.00%,10,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",99.80
5,NP 40,NEVHTWTEQY,10,99.80% (1013/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*26:01, HLA-A*30:02, HLA-A*6...",99.80
6,NP 51,EVHTWTEQYKF,11,99.70% (1012/1015),90.91%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.70
7,NP 6,FVTNEVHTW,9,99.61% (1011/1015),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2...",99.61
8,NP 41,AVHADMGYW,9,99.61% (1011/1015),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3...",99.61
9,NP 14,SQHNYRPGY,9,98.82% (1003/1015),88.89%,100.00%,14,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",98.82
10,NP 31,KAVHADMGY,9,98.42% (999/1015),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",98.42
11,NP 10,FTTNIWLKL,9,98.03% (995/1015),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",98.03
12,NP 38,YWIESEKNETW,11,98.03% (995/1015),72.73%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3...",98.03
13,NP 23,IESEKNETW,9,98.03% (995/1015),66.67%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",98.03
14,NP 36,SEKNETWKL,9,98.03% (995/1015),66.67%,100.00%,11,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",98.03
15,NP 16,TQTAGPWHL,9,97.24% (987/1015),88.89%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",97.24
16,NP 42,QTAGPWHLGK,10,97.04% (985/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.04
17,NP 28,LSAAIGKAW,9,97.04% (985/1015),55.56%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.04
18,NP 30,QTAGPWHLGKL,11,97.04% (985/1015),90.91%,100.00%,12,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",97.04
19,NP 21,SCTLPPLRF,9,96.85% (983/1015),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",96.85
20,NP 29,MWKQISNEL,9,96.55% (980/1015),77.78%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:01, HLA-A*3...",96.55
21,NP 22,ATRLENIMW,9,95.86% (973/1015),55.56%,100.00%,13,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",95.86
22,NP 50,FTQTAGPWHL,10,95.86% (973/1015),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",95.86
23,NP 4,ISNELNHIL,9,95.76% (972/1015),77.78%,100.00%,19,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",95.76