# Análise de dados TCP-CII

### Importação dos parâmetros universais

In [1]:
from pathlib import Path
import importlib.util

path = Path("../../../parametros/config.py").resolve()

spec = importlib.util.spec_from_file_location("parametros", path)
parametros = importlib.util.module_from_spec(spec)
spec.loader.exec_module(parametros)

In [2]:
# Parâmetros importados do arquivo config.py
print("Filtrar por quantidade de alelos TCC1:.........................", parametros.filtarar_por_qte_de_alelos_tcc1)
print("Parâmetro de filtragem median binding percentile TCC1:.........", parametros.parametro_de_filtragem_mbp_tcc1)
print("Percentual de match mínimo TCC1:...............................", parametros.percent_match_minimo_tcc1)

Filtrar por quantidade de alelos TCC1:......................... 10
Parâmetro de filtragem median binding percentile TCC1:......... 5
Percentual de match mínimo TCC1:............................... 95.0

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('./T CELL/DENV 2 - T Cell Prediction - Class I.csv')
df

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTRLENLMW,60,68,9,HLA-B*57:01,60,0.01,VTRLENLMW,VTRLENLMW,0.993804,0.01
1,1,ASGKLITEW,303,311,9,HLA-B*57:01,303,0.01,ASGKLITEW,ASGKLITEW,0.990493,0.01
2,1,ASGKLITEW,303,311,9,HLA-B*58:01,303,0.01,ASGKLITEW,ASGKLITEW,0.989009,0.01
3,1,ETAECPNTNR,139,148,10,HLA-A*68:01,483,0.01,ETAEPNTNR,ETAECPNTNR,0.981131,0.01
4,1,QPTELKYSW,107,115,9,HLA-B*53:01,107,0.01,QPTELKYSW,QPTELKYSW,0.980907,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
36985,1,LKEKEENLVNS,338,348,11,HLA-A*32:01,1025,100.00,KEKENLVNS,KEKEENLVNS,0.000000,100.00
36986,1,LKEKEENLVNS,338,348,11,HLA-B*53:01,1025,100.00,LKEENLVNS,LKEKEENLVNS,0.000000,100.00
36987,1,EKEENLVNSLVT,340,351,12,HLA-A*11:01,1369,100.00,ENLVNSLVT,EKEENLVNSLVT,0.000000,100.00
36988,1,EKEENLVNSLVT,340,351,12,HLA-A*32:01,1369,100.00,EEENLVNSL,EKEENLVNSL,0.000000,100.00
36989,1,EKEENLVNSLVT,340,351,12,HLA-A*68:01,1369,100.00,EKEENLVNT,EKEENLVNSLVT,0.000000,100.00

## Selecionando Epítopos por median binding percentile.

In [6]:
df_mbp_m5 = df[df['median binding percentile'] < parametros.parametro_de_filtragem_mbp_tcc1].copy()
print("Filtrando por median binding percentile < ", parametros.parametro_de_filtragem_mbp_tcc1)
df_mbp_m5

Filtrando por median binding percentile <  5

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTRLENLMW,60,68,9,HLA-B*57:01,60,0.01,VTRLENLMW,VTRLENLMW,0.993804,0.01
1,1,ASGKLITEW,303,311,9,HLA-B*57:01,303,0.01,ASGKLITEW,ASGKLITEW,0.990493,0.01
2,1,ASGKLITEW,303,311,9,HLA-B*58:01,303,0.01,ASGKLITEW,ASGKLITEW,0.989009,0.01
3,1,ETAECPNTNR,139,148,10,HLA-A*68:01,483,0.01,ETAEPNTNR,ETAECPNTNR,0.981131,0.01
4,1,QPTELKYSW,107,115,9,HLA-B*53:01,107,0.01,QPTELKYSW,QPTELKYSW,0.980907,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2519,1,FIEVKNCHW,217,225,9,HLA-A*24:02,217,4.90,FIEVKNCHW,FIEVKNCHW,0.003306,4.90
2520,1,ESEMIIPKNLA,238,248,11,HLA-B*44:02,925,4.90,EEMIIPKNL,ESEMIIPKNL,0.002875,4.90
2521,1,MEIRPLKEKE,333,342,10,HLA-B*44:02,677,4.90,MEIRPLKKE,MEIRPLKEKE,0.002854,4.90
2522,1,FIEVKNCHW,217,225,9,HLA-B*44:02,217,4.90,FIEVKNCHW,FIEVKNCHW,0.002809,4.90
2523,1,TQITGPWHLGKL,262,273,12,HLA-B*40:01,1291,4.90,TQITGPWHL,TQITGPWHLGKL,0.002679,4.90

## Agrupando por pepitideos e agregando colunas pertinentes

In [7]:
epitopos_repetidos = (
    df_mbp_m5
    .groupby('peptide', as_index=False)
    .agg(
        start=("start", "first"),
        end=("end", "first"),
        qte_de_alelos=("allele", "nunique"),
        median_binding_percentile=(
            "median binding percentile",
            "median"
        ),
        alelos=(
            "allele",
            lambda x: ", ".join(sorted(x.unique()))
        )
    )
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,AAIKDNRAV,186,194,7,2.70,"HLA-A*02:03, HLA-A*02:06, HLA-A*68:02, HLA-B*0..."
1,AAIKDNRAVH,186,195,2,4.20,"HLA-A*30:02, HLA-B*15:01"
2,ADMGYWIESAL,196,206,1,3.00,HLA-B*40:01
3,AECPNTNRA,141,149,3,1.00,"HLA-B*40:01, HLA-B*44:02, HLA-B*44:03"
4,AECPNTNRAW,141,150,8,1.70,"HLA-A*01:01, HLA-A*23:01, HLA-B*40:01, HLA-B*4..."
...,...,...,...,...,...,...
585,YSWKTWGKA,113,121,2,4.40,"HLA-A*30:02, HLA-A*68:02"
586,YSWKTWGKAK,113,122,6,2.05,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
587,YSWKTWGKAKM,113,123,2,2.40,"HLA-B*57:01, HLA-B*58:01"
588,YWIESALNDTW,200,210,9,1.10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*4..."
589,YWIESALNDTWK,200,211,2,4.25,"HLA-A*23:01, HLA-A*24:02"

## Filtragem por qte_de_alelos

In [8]:
filtarar_por_qte_de_alelos = 10

In [9]:
# Filtro do número de alelos
epitopos_repetidos = epitopos_repetidos[
    epitopos_repetidos["qte_de_alelos"] >= filtarar_por_qte_de_alelos
].reset_index(drop=True)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,ASGKLITEW,303,311,12,1.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
1,AVHADMGYW,193,201,10,1.645,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
2,CHWPKSHTL,223,231,12,2.600,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3..."
3,CTLPPLRYR,316,324,11,0.960,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
4,DTWKIEKASF,208,217,12,2.950,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
5,ELKYSWKTW,110,118,11,1.500,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
6,FIEVKNCHW,217,225,10,3.200,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
7,FITDNVHTW,20,28,22,1.150,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
8,FQPESPSKL,34,42,18,1.600,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
9,FTTNIWLKL,163,171,16,1.650,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
10,GIFITDNVHTW,18,28,10,0.770,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
11,HTQITGPWHL,261,270,13,1.700,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
12,HTWTEQYKF,26,34,21,1.500,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
13,HWPKSHTLW,224,232,14,2.450,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
14,IESALNDTW,202,210,10,1.150,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."
15,IFITDNVHTW,19,28,11,0.340,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
16,ILSENEVKL,78,86,13,2.800,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
17,IMQAGKRSL,96,104,11,2.200,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
18,ITGPWHLGK,264,272,11,2.600,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
19,ITPELNHIL,71,79,17,1.700,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
20,KFQPESPSKL,33,42,12,2.550,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
21,KLKEKQDVF,170,178,20,2.100,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
22,KQITPELNH,69,77,10,2.350,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
23,KQITPELNHI,69,78,11,2.900,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
24,KQITPELNHIL,69,79,10,2.250,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
25,KRSLRPQPTEL,101,111,10,2.250,"HLA-A*02:01, HLA-A*02:03, HLA-A*30:01, HLA-A*3..."
26,KTWGKAKML,116,124,18,2.400,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
27,LRPQPTELKY,104,113,14,3.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
28,LSTESHNQTF,124,133,10,2.400,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
29,MLSTESHNQTF,123,133,11,1.800,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
30,MWKQITPEL,67,75,17,2.200,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
31,NLAGPVSQH,246,254,10,3.250,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1..."
32,NTNRAWNSL,145,153,12,3.550,"HLA-A*01:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
33,NVHTWTEQY,24,32,16,1.550,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
34,QITPELNHI,70,78,12,2.850,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
35,QPTELKYSW,107,115,14,0.835,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
36,RAVHADMGY,192,200,12,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
37,RPQPTELKY,105,113,19,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
38,RPQPTELKYSW,105,115,12,1.350,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
39,RSCTLPPLR,314,322,10,1.950,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
40,RSCTLPPLRY,314,323,11,1.300,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
41,RSCTLPPLRYR,314,324,11,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
42,RSLRPQPTEL,102,111,14,1.080,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
43,RSLRPQPTELKY,102,113,12,0.820,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
44,RSVTRLENL,58,66,11,2.300,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
45,SALNDTWKI,204,212,11,1.400,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
46,SCTLPPLRY,315,323,13,2.000,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
47,SCTLPPLRYR,315,324,10,0.660,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
48,SEMIIPKNL,239,247,11,4.100,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-B*0..."
49,SENEVKLTI,80,88,18,3.000,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
50,SLRPQPTEL,103,111,21,2.500,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
51,SLRPQPTELK,103,112,11,1.900,"HLA-A*02:03, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
52,SLRPQPTELKY,103,113,16,1.350,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
53,SQHNYRPGY,252,260,14,1.285,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
54,STESHNQTF,125,133,18,1.200,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
55,SVTRLENLM,59,67,10,3.800,"HLA-A*02:06, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
56,TASGKLITEW,302,311,11,2.800,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
57,TQITGPWHL,262,270,22,1.750,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
58,VEDYGFGVF,155,163,11,3.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
59,VTRLENLMW,60,68,12,3.250,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

## Sorting por median_biding_percentile

In [10]:
epitopos_repetidos = (
    epitopos_repetidos
    .sort_values(
        ["median_binding_percentile", "qte_de_alelos"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,IFITDNVHTW,19,28,11,0.340,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
1,SCTLPPLRYR,315,324,10,0.660,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
2,GIFITDNVHTW,18,28,10,0.770,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
3,RSLRPQPTELKY,102,113,12,0.820,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
4,QPTELKYSW,107,115,14,0.835,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
5,CTLPPLRYR,316,324,11,0.960,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
6,RSLRPQPTEL,102,111,14,1.080,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
7,FITDNVHTW,20,28,22,1.150,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
8,IESALNDTW,202,210,10,1.150,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."
9,STESHNQTF,125,133,18,1.200,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
10,RAVHADMGY,192,200,12,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
11,SQHNYRPGY,252,260,14,1.285,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
12,RSCTLPPLRY,314,323,11,1.300,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
13,SLRPQPTELKY,103,113,16,1.350,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
14,RPQPTELKYSW,105,115,12,1.350,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
15,RPQPTELKY,105,113,19,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
16,RSCTLPPLRYR,314,324,11,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
17,SALNDTWKI,204,212,11,1.400,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
18,HTWTEQYKF,26,34,21,1.500,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
19,ELKYSWKTW,110,118,11,1.500,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
20,NVHTWTEQY,24,32,16,1.550,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
21,FQPESPSKL,34,42,18,1.600,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
22,ASGKLITEW,303,311,12,1.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
23,AVHADMGYW,193,201,10,1.645,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
24,FTTNIWLKL,163,171,16,1.650,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
25,ITPELNHIL,71,79,17,1.700,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
26,HTQITGPWHL,261,270,13,1.700,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
27,TQITGPWHL,262,270,22,1.750,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
28,MLSTESHNQTF,123,133,11,1.800,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
29,SLRPQPTELK,103,112,11,1.900,"HLA-A*02:03, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
30,RSCTLPPLR,314,322,10,1.950,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
31,SCTLPPLRY,315,323,13,2.000,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
32,KLKEKQDVF,170,178,20,2.100,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
33,MWKQITPEL,67,75,17,2.200,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
34,IMQAGKRSL,96,104,11,2.200,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
35,KQITPELNHIL,69,79,10,2.250,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
36,KRSLRPQPTEL,101,111,10,2.250,"HLA-A*02:01, HLA-A*02:03, HLA-A*30:01, HLA-A*3..."
37,RSVTRLENL,58,66,11,2.300,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
38,KQITPELNH,69,77,10,2.350,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
39,KTWGKAKML,116,124,18,2.400,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
40,LSTESHNQTF,124,133,10,2.400,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
41,HWPKSHTLW,224,232,14,2.450,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
42,SLRPQPTEL,103,111,21,2.500,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
43,KFQPESPSKL,33,42,12,2.550,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
44,CHWPKSHTL,223,231,12,2.600,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3..."
45,ITGPWHLGK,264,272,11,2.600,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
46,ILSENEVKL,78,86,13,2.800,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
47,TASGKLITEW,302,311,11,2.800,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
48,QITPELNHI,70,78,12,2.850,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
49,KQITPELNHI,69,78,11,2.900,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
50,DTWKIEKASF,208,217,12,2.950,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
51,SENEVKLTI,80,88,18,3.000,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
52,LRPQPTELKY,104,113,14,3.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
53,FIEVKNCHW,217,225,10,3.200,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
54,VTRLENLMW,60,68,12,3.250,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
55,NLAGPVSQH,246,254,10,3.250,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1..."
56,VEDYGFGVF,155,163,11,3.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
57,NTNRAWNSL,145,153,12,3.550,"HLA-A*01:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
58,SVTRLENLM,59,67,10,3.800,"HLA-A*02:06, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
59,SEMIIPKNL,239,247,11,4.100,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-B*0..."

## Separando epítopos e criando arquivo FASTA para IEDB analysis resource

In [11]:
pepitides = epitopos_repetidos.peptide

with open("./peptideos_tcell_1.fasta", "w") as f:
    for i, peptide in enumerate(pepitides, start=1):
        f.write(f">NP {i}\n")
        f.write(f"{peptide}\n")
        
pepitides

0       IFITDNVHTW
1       SCTLPPLRYR
2      GIFITDNVHTW
3     RSLRPQPTELKY
4        QPTELKYSW
5        CTLPPLRYR
6       RSLRPQPTEL
7        FITDNVHTW
8        IESALNDTW
9        STESHNQTF
10       RAVHADMGY
11       SQHNYRPGY
12      RSCTLPPLRY
13     SLRPQPTELKY
14     RPQPTELKYSW
15       RPQPTELKY
16     RSCTLPPLRYR
17       SALNDTWKI
18       HTWTEQYKF
19       ELKYSWKTW
20       NVHTWTEQY
21       FQPESPSKL
22       ASGKLITEW
23       AVHADMGYW
24       FTTNIWLKL
25       ITPELNHIL
26      HTQITGPWHL
27       TQITGPWHL
28     MLSTESHNQTF
29      SLRPQPTELK
30       RSCTLPPLR
31       SCTLPPLRY
32       KLKEKQDVF
33       MWKQITPEL
34       IMQAGKRSL
35     KQITPELNHIL
36     KRSLRPQPTEL
37       RSVTRLENL
38       KQITPELNH
39       KTWGKAKML
40      LSTESHNQTF
41       HWPKSHTLW
42       SLRPQPTEL
43      KFQPESPSKL
44       CHWPKSHTL
45       ITGPWHLGK
46       ILSENEVKL
47      TASGKLITEW
48       QITPELNHI
49      KQITPELNHI
50      DTWKIEKASF
51       SENEVKLTI
52      LRPQPTELKY
53       FIEVKNCHW
54       VTRLENLMW
55       NLAGPVSQH
56       VEDYGFGVF
57       NTNRAWNSL
58       SVTRLENLM
59       SEMIIPKNL
Name: peptide, dtype: str

### Seqkit remove sequências proteicas contendo gaps e *.

In [12]:
# !seqkit grep -s -v -r -p '[-*]' './Fastas/denv1_NS1_proteinas.fa' > DENV1_seq_filter_all.fasta

### Resultado IEDB analysis resource

In [13]:
conservacy_result = pd.read_csv('./ConservancyResult_tcell_1.csv')
conservacy_result

,Epitope #,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,View details
0,1,NP 1,FITDNVHTW,9,97.00% (840/866),88.89%,100.00%,NaN
1,2,NP 2,TQITGPWHL,9,0.81% (7/866),55.56%,100.00%,NaN
2,3,NP 3,HTWTEQYKF,9,99.77% (864/866),88.89%,100.00%,NaN
3,4,NP 4,SLRPQPTEL,9,93.19% (807/866),66.67%,100.00%,NaN
4,5,NP 5,KLKEKQDVF,9,3.35% (29/866),66.67%,100.00%,NaN
5,6,NP 6,RPQPTELKY,9,97.58% (845/866),55.56%,100.00%,NaN
6,7,NP 7,STESHNQTF,9,44.11% (382/866),66.67%,100.00%,NaN
7,8,NP 8,FQPESPSKL,9,99.42% (861/866),88.89%,100.00%,NaN
8,9,NP 9,KTWGKAKML,9,69.98% (606/866),77.78%,100.00%,NaN
9,10,NP 10,SENEVKLTI,9,52.89% (458/866),77.78%,100.00%,NaN
10,11,NP 11,ITPELNHIL,9,97.46% (844/866),88.89%,100.00%,NaN
11,12,NP 12,MWKQITPEL,9,97.34% (843/866),88.89%,100.00%,NaN
12,13,NP 13,SLRPQPTELKY,11,92.03% (797/866),63.64%,100.00%,NaN
13,14,NP 14,NVHTWTEQY,9,99.88% (865/866),88.89%,100.00%,NaN
14,15,NP 15,FTTNIWLKL,9,89.26% (773/866),88.89%,100.00%,NaN
15,16,NP 16,QPTELKYSW,9,97.81% (847/866),44.44%,100.00%,NaN
16,17,NP 17,RSLRPQPTEL,10,93.19% (807/866),70.00%,100.00%,NaN
17,18,NP 18,SQHNYRPGY,9,97.81% (847/866),88.89%,100.00%,NaN
18,19,NP 19,HWPKSHTLW,9,97.46% (844/866),55.56%,100.00%,NaN
19,20,NP 20,LRPQPTELKY,10,97.46% (844/866),60.00%,100.00%,NaN
20,21,NP 21,HTQITGPWHL,10,0.81% (7/866),60.00%,100.00%,NaN
21,22,NP 22,SCTLPPLRY,9,99.77% (864/866),88.89%,100.00%,NaN
22,23,NP 23,ILSENEVKL,9,53.23% (461/866),77.78%,100.00%,NaN
23,24,NP 24,RSLRPQPTELKY,12,92.03% (797/866),66.67%,100.00%,NaN
24,25,NP 25,RAVHADMGY,9,97.34% (843/866),88.89%,100.00%,NaN
25,26,NP 26,RPQPTELKYSW,11,97.23% (842/866),54.55%,100.00%,NaN
26,27,NP 27,ASGKLITEW,9,99.42% (861/866),88.89%,100.00%,NaN
27,28,NP 28,KFQPESPSKL,10,99.19% (859/866),90.00%,100.00%,NaN
28,29,NP 29,CHWPKSHTL,9,97.58% (845/866),55.56%,100.00%,NaN
29,30,NP 30,QITPELNHI,9,97.58% (845/866),88.89%,100.00%,NaN
30,31,NP 31,DTWKIEKASF,10,55.54% (481/866),60.00%,100.00%,NaN
31,32,NP 32,VTRLENLMW,9,99.19% (859/866),55.56%,100.00%,NaN
32,33,NP 33,NTNRAWNSL,9,95.96% (831/866),88.89%,100.00%,NaN
33,34,NP 34,IFITDNVHTW,10,97.00% (840/866),90.00%,100.00%,NaN
34,35,NP 35,CTLPPLRYR,9,95.84% (830/866),88.89%,100.00%,NaN
35,36,NP 36,RSCTLPPLRY,10,99.77% (864/866),90.00%,100.00%,NaN
36,37,NP 37,RSCTLPPLRYR,11,95.84% (830/866),90.91%,100.00%,NaN
37,38,NP 38,SALNDTWKI,9,60.16% (521/866),44.44%,100.00%,NaN
38,39,NP 39,ELKYSWKTW,9,69.40% (601/866),66.67%,100.00%,NaN
39,40,NP 40,MLSTESHNQTF,11,43.65% (378/866),63.64%,100.00%,NaN
40,41,NP 41,SLRPQPTELK,10,92.03% (797/866),70.00%,100.00%,NaN
41,42,NP 42,IMQAGKRSL,9,91.34% (791/866),88.89%,100.00%,NaN
42,43,NP 43,RSVTRLENL,9,99.19% (859/866),55.56%,100.00%,NaN
43,44,NP 44,ITGPWHLGK,9,0.81% (7/866),55.56%,100.00%,NaN
44,45,NP 45,TASGKLITEW,10,99.42% (861/866),90.00%,100.00%,NaN
45,46,NP 46,KQITPELNHI,10,97.23% (842/866),90.00%,100.00%,NaN
46,47,NP 47,VEDYGFGVF,9,99.77% (864/866),88.89%,100.00%,NaN
47,48,NP 48,SEMIIPKNL,9,23.44% (203/866),66.67%,100.00%,NaN
48,49,NP 49,SCTLPPLRYR,10,95.84% (830/866),90.00%,100.00%,NaN
49,50,NP 50,GIFITDNVHTW,11,97.00% (840/866),90.91%,100.00%,NaN
50,51,NP 51,IESALNDTW,9,97.58% (845/866),44.44%,100.00%,NaN
51,52,NP 52,AVHADMGYW,9,97.46% (844/866),88.89%,100.00%,NaN
52,53,NP 53,RSCTLPPLR,9,99.88% (865/866),88.89%,100.00%,NaN
53,54,NP 54,KQITPELNHIL,11,97.11% (841/866),90.91%,100.00%,NaN
54,55,NP 55,KRSLRPQPTEL,11,92.84% (804/866),72.73%,100.00%,NaN
55,56,NP 56,KQITPELNH,9,97.23% (842/866),88.89%,100.00%,NaN
56,57,NP 57,LSTESHNQTF,10,43.88% (380/866),60.00%,100.00%,NaN
57,58,NP 58,FIEVKNCHW,9,21.82% (189/866),66.67%,100.00%,NaN
58,59,NP 59,NLAGPVSQH,9,23.67% (205/866),77.78%,100.00%,NaN
59,60,NP 60,SVTRLENLM,9,99.19% (859/866),55.56%,100.00%,NaN

### Merge da coluna qte_de_alelos ao dataframe conservacy_result

In [14]:
# qte_de_alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "qte_de_alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("View details"))

# alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("Epitope #"))

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos
0,NP 1,FITDNVHTW,9,97.00% (840/866),88.89%,100.00%,22,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
1,NP 2,TQITGPWHL,9,0.81% (7/866),55.56%,100.00%,22,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
2,NP 3,HTWTEQYKF,9,99.77% (864/866),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
3,NP 4,SLRPQPTEL,9,93.19% (807/866),66.67%,100.00%,21,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
4,NP 5,KLKEKQDVF,9,3.35% (29/866),66.67%,100.00%,20,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
5,NP 6,RPQPTELKY,9,97.58% (845/866),55.56%,100.00%,19,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
6,NP 7,STESHNQTF,9,44.11% (382/866),66.67%,100.00%,18,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
7,NP 8,FQPESPSKL,9,99.42% (861/866),88.89%,100.00%,18,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
8,NP 9,KTWGKAKML,9,69.98% (606/866),77.78%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
9,NP 10,SENEVKLTI,9,52.89% (458/866),77.78%,100.00%,18,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
10,NP 11,ITPELNHIL,9,97.46% (844/866),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
11,NP 12,MWKQITPEL,9,97.34% (843/866),88.89%,100.00%,17,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
12,NP 13,SLRPQPTELKY,11,92.03% (797/866),63.64%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
13,NP 14,NVHTWTEQY,9,99.88% (865/866),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
14,NP 15,FTTNIWLKL,9,89.26% (773/866),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
15,NP 16,QPTELKYSW,9,97.81% (847/866),44.44%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
16,NP 17,RSLRPQPTEL,10,93.19% (807/866),70.00%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
17,NP 18,SQHNYRPGY,9,97.81% (847/866),88.89%,100.00%,14,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
18,NP 19,HWPKSHTLW,9,97.46% (844/866),55.56%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
19,NP 20,LRPQPTELKY,10,97.46% (844/866),60.00%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
20,NP 21,HTQITGPWHL,10,0.81% (7/866),60.00%,100.00%,13,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
21,NP 22,SCTLPPLRY,9,99.77% (864/866),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
22,NP 23,ILSENEVKL,9,53.23% (461/866),77.78%,100.00%,13,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
23,NP 24,RSLRPQPTELKY,12,92.03% (797/866),66.67%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
24,NP 25,RAVHADMGY,9,97.34% (843/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
25,NP 26,RPQPTELKYSW,11,97.23% (842/866),54.55%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
26,NP 27,ASGKLITEW,9,99.42% (861/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
27,NP 28,KFQPESPSKL,10,99.19% (859/866),90.00%,100.00%,12,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
28,NP 29,CHWPKSHTL,9,97.58% (845/866),55.56%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3..."
29,NP 30,QITPELNHI,9,97.58% (845/866),88.89%,100.00%,12,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
30,NP 31,DTWKIEKASF,10,55.54% (481/866),60.00%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
31,NP 32,VTRLENLMW,9,99.19% (859/866),55.56%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
32,NP 33,NTNRAWNSL,9,95.96% (831/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
33,NP 34,IFITDNVHTW,10,97.00% (840/866),90.00%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
34,NP 35,CTLPPLRYR,9,95.84% (830/866),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
35,NP 36,RSCTLPPLRY,10,99.77% (864/866),90.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
36,NP 37,RSCTLPPLRYR,11,95.84% (830/866),90.91%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
37,NP 38,SALNDTWKI,9,60.16% (521/866),44.44%,100.00%,11,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
38,NP 39,ELKYSWKTW,9,69.40% (601/866),66.67%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
39,NP 40,MLSTESHNQTF,11,43.65% (378/866),63.64%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
40,NP 41,SLRPQPTELK,10,92.03% (797/866),70.00%,100.00%,11,"HLA-A*02:03, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
41,NP 42,IMQAGKRSL,9,91.34% (791/866),88.89%,100.00%,11,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
42,NP 43,RSVTRLENL,9,99.19% (859/866),55.56%,100.00%,11,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
43,NP 44,ITGPWHLGK,9,0.81% (7/866),55.56%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
44,NP 45,TASGKLITEW,10,99.42% (861/866),90.00%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
45,NP 46,KQITPELNHI,10,97.23% (842/866),90.00%,100.00%,11,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
46,NP 47,VEDYGFGVF,9,99.77% (864/866),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
47,NP 48,SEMIIPKNL,9,23.44% (203/866),66.67%,100.00%,11,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-B*0..."
48,NP 49,SCTLPPLRYR,10,95.84% (830/866),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
49,NP 50,GIFITDNVHTW,11,97.00% (840/866),90.91%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
50,NP 51,IESALNDTW,9,97.58% (845/866),44.44%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."
51,NP 52,AVHADMGYW,9,97.46% (844/866),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
52,NP 53,RSCTLPPLR,9,99.88% (865/866),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
53,NP 54,KQITPELNHIL,11,97.11% (841/866),90.91%,100.00%,10,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
54,NP 55,KRSLRPQPTEL,11,92.84% (804/866),72.73%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*30:01, HLA-A*3..."
55,NP 56,KQITPELNH,9,97.23% (842/866),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
56,NP 57,LSTESHNQTF,10,43.88% (380/866),60.00%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
57,NP 58,FIEVKNCHW,9,21.82% (189/866),66.67%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
58,NP 59,NLAGPVSQH,9,23.67% (205/866),77.78%,100.00%,10,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1..."
59,NP 60,SVTRLENLM,9,99.19% (859/866),55.56%,100.00%,10,"HLA-A*02:06, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."

### Gerando a coluna percent_match para filtrar os epitopos com percentagem de match maior que 50%

In [15]:
col = "Percent of protein sequence matches at identity <= 100%"

conservacy_result["percent_match"] = (
    conservacy_result[col]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
    .astype(float)
)

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos,percent_match
0,NP 1,FITDNVHTW,9,97.00% (840/866),88.89%,100.00%,22,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",97.00
1,NP 2,TQITGPWHL,9,0.81% (7/866),55.56%,100.00%,22,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",0.81
2,NP 3,HTWTEQYKF,9,99.77% (864/866),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2...",99.77
3,NP 4,SLRPQPTEL,9,93.19% (807/866),66.67%,100.00%,21,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",93.19
4,NP 5,KLKEKQDVF,9,3.35% (29/866),66.67%,100.00%,20,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",3.35
5,NP 6,RPQPTELKY,9,97.58% (845/866),55.56%,100.00%,19,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.58
6,NP 7,STESHNQTF,9,44.11% (382/866),66.67%,100.00%,18,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",44.11
7,NP 8,FQPESPSKL,9,99.42% (861/866),88.89%,100.00%,18,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",99.42
8,NP 9,KTWGKAKML,9,69.98% (606/866),77.78%,100.00%,18,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0...",69.98
9,NP 10,SENEVKLTI,9,52.89% (458/866),77.78%,100.00%,18,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2...",52.89
10,NP 11,ITPELNHIL,9,97.46% (844/866),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",97.46
11,NP 12,MWKQITPEL,9,97.34% (843/866),88.89%,100.00%,17,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",97.34
12,NP 13,SLRPQPTELKY,11,92.03% (797/866),63.64%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",92.03
13,NP 14,NVHTWTEQY,9,99.88% (865/866),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.88
14,NP 15,FTTNIWLKL,9,89.26% (773/866),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",89.26
15,NP 16,QPTELKYSW,9,97.81% (847/866),44.44%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.81
16,NP 17,RSLRPQPTEL,10,93.19% (807/866),70.00%,100.00%,14,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0...",93.19
17,NP 18,SQHNYRPGY,9,97.81% (847/866),88.89%,100.00%,14,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",97.81
18,NP 19,HWPKSHTLW,9,97.46% (844/866),55.56%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.46
19,NP 20,LRPQPTELKY,10,97.46% (844/866),60.00%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.46
20,NP 21,HTQITGPWHL,10,0.81% (7/866),60.00%,100.00%,13,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",0.81
21,NP 22,SCTLPPLRY,9,99.77% (864/866),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.77
22,NP 23,ILSENEVKL,9,53.23% (461/866),77.78%,100.00%,13,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",53.23
23,NP 24,RSLRPQPTELKY,12,92.03% (797/866),66.67%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3...",92.03
24,NP 25,RAVHADMGY,9,97.34% (843/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.34
25,NP 26,RPQPTELKYSW,11,97.23% (842/866),54.55%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0...",97.23
26,NP 27,ASGKLITEW,9,99.42% (861/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.42
27,NP 28,KFQPESPSKL,10,99.19% (859/866),90.00%,100.00%,12,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",99.19
28,NP 29,CHWPKSHTL,9,97.58% (845/866),55.56%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3...",97.58
29,NP 30,QITPELNHI,9,97.58% (845/866),88.89%,100.00%,12,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",97.58
30,NP 31,DTWKIEKASF,10,55.54% (481/866),60.00%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",55.54
31,NP 32,VTRLENLMW,9,99.19% (859/866),55.56%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.19
32,NP 33,NTNRAWNSL,9,95.96% (831/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",95.96
33,NP 34,IFITDNVHTW,10,97.00% (840/866),90.00%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",97.00
34,NP 35,CTLPPLRYR,9,95.84% (830/866),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",95.84
35,NP 36,RSCTLPPLRY,10,99.77% (864/866),90.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.77
36,NP 37,RSCTLPPLRYR,11,95.84% (830/866),90.91%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3...",95.84
37,NP 38,SALNDTWKI,9,60.16% (521/866),44.44%,100.00%,11,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",60.16
38,NP 39,ELKYSWKTW,9,69.40% (601/866),66.67%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",69.40
39,NP 40,MLSTESHNQTF,11,43.65% (378/866),63.64%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",43.65
40,NP 41,SLRPQPTELK,10,92.03% (797/866),70.00%,100.00%,11,"HLA-A*02:03, HLA-A*03:01, HLA-A*11:01, HLA-A*3...",92.03
41,NP 42,IMQAGKRSL,9,91.34% (791/866),88.89%,100.00%,11,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",91.34
42,NP 43,RSVTRLENL,9,99.19% (859/866),55.56%,100.00%,11,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*3...",99.19
43,NP 44,ITGPWHLGK,9,0.81% (7/866),55.56%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3...",0.81
44,NP 45,TASGKLITEW,10,99.42% (861/866),90.00%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",99.42
45,NP 46,KQITPELNHI,10,97.23% (842/866),90.00%,100.00%,11,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",97.23
46,NP 47,VEDYGFGVF,9,99.77% (864/866),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.77
47,NP 48,SEMIIPKNL,9,23.44% (203/866),66.67%,100.00%,11,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-B*0...",23.44
48,NP 49,SCTLPPLRYR,10,95.84% (830/866),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",95.84
49,NP 50,GIFITDNVHTW,11,97.00% (840/866),90.91%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",97.00
50,NP 51,IESALNDTW,9,97.58% (845/866),44.44%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3...",97.58
51,NP 52,AVHADMGYW,9,97.46% (844/866),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3...",97.46
52,NP 53,RSCTLPPLR,9,99.88% (865/866),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",99.88
53,NP 54,KQITPELNHIL,11,97.11% (841/866),90.91%,100.00%,10,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",97.11
54,NP 55,KRSLRPQPTEL,11,92.84% (804/866),72.73%,100.00%,10,"HLA-A*02:01, HLA-A*02:03, HLA-A*30:01, HLA-A*3...",92.84
55,NP 56,KQITPELNH,9,97.23% (842/866),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",97.23
56,NP 57,LSTESHNQTF,10,43.88% (380/866),60.00%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",43.88
57,NP 58,FIEVKNCHW,9,21.82% (189/866),66.67%,100.00%,10,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3...",21.82
58,NP 59,NLAGPVSQH,9,23.67% (205/866),77.78%,100.00%,10,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1...",23.67
59,NP 60,SVTRLENLM,9,99.19% (859/866),55.56%,100.00%,10,"HLA-A*02:06, HLA-A*26:01, HLA-A*30:02, HLA-A*3...",99.19

### Sort e filtragem por percent_match e presença em alelos

In [16]:
# Parametros
percent_match_minimo = 95.0

In [17]:
# Filtro do Percent match
conservacy_result_filtered = (
    conservacy_result[conservacy_result["percent_match"] >= percent_match_minimo]
    .sort_values(
            by="percent_match", 
            ascending=False
        )
    ).reset_index(drop=True)

conservacy_result_filtered

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,alelos,percent_match
0,NP 53,RSCTLPPLR,9,99.88% (865/866),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",99.88
1,NP 14,NVHTWTEQY,9,99.88% (865/866),88.89%,100.00%,16,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.88
2,NP 3,HTWTEQYKF,9,99.77% (864/866),88.89%,100.00%,21,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2...",99.77
3,NP 36,RSCTLPPLRY,10,99.77% (864/866),90.00%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.77
4,NP 47,VEDYGFGVF,9,99.77% (864/866),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.77
5,NP 22,SCTLPPLRY,9,99.77% (864/866),88.89%,100.00%,13,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",99.77
6,NP 8,FQPESPSKL,9,99.42% (861/866),88.89%,100.00%,18,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",99.42
7,NP 45,TASGKLITEW,10,99.42% (861/866),90.00%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",99.42
8,NP 27,ASGKLITEW,9,99.42% (861/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.42
9,NP 60,SVTRLENLM,9,99.19% (859/866),55.56%,100.00%,10,"HLA-A*02:06, HLA-A*26:01, HLA-A*30:02, HLA-A*3...",99.19
10,NP 32,VTRLENLMW,9,99.19% (859/866),55.56%,100.00%,12,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.19
11,NP 28,KFQPESPSKL,10,99.19% (859/866),90.00%,100.00%,12,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",99.19
12,NP 43,RSVTRLENL,9,99.19% (859/866),55.56%,100.00%,11,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*3...",99.19
13,NP 18,SQHNYRPGY,9,97.81% (847/866),88.89%,100.00%,14,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1...",97.81
14,NP 16,QPTELKYSW,9,97.81% (847/866),44.44%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.81
15,NP 6,RPQPTELKY,9,97.58% (845/866),55.56%,100.00%,19,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.58
16,NP 30,QITPELNHI,9,97.58% (845/866),88.89%,100.00%,12,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",97.58
17,NP 51,IESALNDTW,9,97.58% (845/866),44.44%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3...",97.58
18,NP 29,CHWPKSHTL,9,97.58% (845/866),55.56%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3...",97.58
19,NP 19,HWPKSHTLW,9,97.46% (844/866),55.56%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.46
20,NP 20,LRPQPTELKY,10,97.46% (844/866),60.00%,100.00%,14,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",97.46
21,NP 11,ITPELNHIL,9,97.46% (844/866),88.89%,100.00%,17,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",97.46
22,NP 52,AVHADMGYW,9,97.46% (844/866),88.89%,100.00%,10,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3...",97.46
23,NP 25,RAVHADMGY,9,97.34% (843/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",97.34
24,NP 12,MWKQITPEL,9,97.34% (843/866),88.89%,100.00%,17,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",97.34
25,NP 46,KQITPELNHI,10,97.23% (842/866),90.00%,100.00%,11,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2...",97.23
26,NP 56,KQITPELNH,9,97.23% (842/866),88.89%,100.00%,10,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3...",97.23
27,NP 26,RPQPTELKYSW,11,97.23% (842/866),54.55%,100.00%,12,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0...",97.23
28,NP 54,KQITPELNHIL,11,97.11% (841/866),90.91%,100.00%,10,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2...",97.11
29,NP 1,FITDNVHTW,9,97.00% (840/866),88.89%,100.00%,22,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0...",97.00
30,NP 50,GIFITDNVHTW,11,97.00% (840/866),90.91%,100.00%,10,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",97.00
31,NP 34,IFITDNVHTW,10,97.00% (840/866),90.00%,100.00%,11,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",97.00
32,NP 33,NTNRAWNSL,9,95.96% (831/866),88.89%,100.00%,12,"HLA-A*01:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3...",95.96
33,NP 37,RSCTLPPLRYR,11,95.84% (830/866),90.91%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3...",95.84
34,NP 35,CTLPPLRYR,9,95.84% (830/866),88.89%,100.00%,11,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",95.84
35,NP 49,SCTLPPLRYR,10,95.84% (830/866),90.00%,100.00%,10,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2...",95.84