# Análise de dados TCP-CI

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./T CELL/DENV 2 - T Cell Prediction - Class I.csv')
df

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTRLENLMW,60,68,9,HLA-B*57:01,60,0.01,VTRLENLMW,VTRLENLMW,0.993804,0.01
1,1,ASGKLITEW,303,311,9,HLA-B*57:01,303,0.01,ASGKLITEW,ASGKLITEW,0.990493,0.01
2,1,ASGKLITEW,303,311,9,HLA-B*58:01,303,0.01,ASGKLITEW,ASGKLITEW,0.989009,0.01
3,1,ETAECPNTNR,139,148,10,HLA-A*68:01,483,0.01,ETAEPNTNR,ETAECPNTNR,0.981131,0.01
4,1,QPTELKYSW,107,115,9,HLA-B*53:01,107,0.01,QPTELKYSW,QPTELKYSW,0.980907,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
36985,1,LKEKEENLVNS,338,348,11,HLA-A*32:01,1025,100.00,KEKENLVNS,KEKEENLVNS,0.000000,100.00
36986,1,LKEKEENLVNS,338,348,11,HLA-B*53:01,1025,100.00,LKEENLVNS,LKEKEENLVNS,0.000000,100.00
36987,1,EKEENLVNSLVT,340,351,12,HLA-A*11:01,1369,100.00,ENLVNSLVT,EKEENLVNSLVT,0.000000,100.00
36988,1,EKEENLVNSLVT,340,351,12,HLA-A*32:01,1369,100.00,EEENLVNSL,EKEENLVNSL,0.000000,100.00
36989,1,EKEENLVNSLVT,340,351,12,HLA-A*68:01,1369,100.00,EKEENLVNT,EKEENLVNSLVT,0.000000,100.00

## Selecionando Epítopos com median binding percentile menor que 5.

In [3]:
df_mbp_m5 = df[df['median binding percentile'] < 5].copy()
df_mbp_m5

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTRLENLMW,60,68,9,HLA-B*57:01,60,0.01,VTRLENLMW,VTRLENLMW,0.993804,0.01
1,1,ASGKLITEW,303,311,9,HLA-B*57:01,303,0.01,ASGKLITEW,ASGKLITEW,0.990493,0.01
2,1,ASGKLITEW,303,311,9,HLA-B*58:01,303,0.01,ASGKLITEW,ASGKLITEW,0.989009,0.01
3,1,ETAECPNTNR,139,148,10,HLA-A*68:01,483,0.01,ETAEPNTNR,ETAECPNTNR,0.981131,0.01
4,1,QPTELKYSW,107,115,9,HLA-B*53:01,107,0.01,QPTELKYSW,QPTELKYSW,0.980907,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2519,1,FIEVKNCHW,217,225,9,HLA-A*24:02,217,4.90,FIEVKNCHW,FIEVKNCHW,0.003306,4.90
2520,1,ESEMIIPKNLA,238,248,11,HLA-B*44:02,925,4.90,EEMIIPKNL,ESEMIIPKNL,0.002875,4.90
2521,1,MEIRPLKEKE,333,342,10,HLA-B*44:02,677,4.90,MEIRPLKKE,MEIRPLKEKE,0.002854,4.90
2522,1,FIEVKNCHW,217,225,9,HLA-B*44:02,217,4.90,FIEVKNCHW,FIEVKNCHW,0.002809,4.90
2523,1,TQITGPWHLGKL,262,273,12,HLA-B*40:01,1291,4.90,TQITGPWHL,TQITGPWHLGKL,0.002679,4.90

## Agrupando por pepitideos e agregando colunas pertinentes.

In [4]:
epitopos_repetidos = (
    df_mbp_m5
    .groupby('peptide', as_index=False)
    .agg(
        start=("start", "first"),
        end=("end", "first"),
        qte_de_alelos=("allele", "nunique"),
        median_binding_percentile=(
            "median binding percentile",
            "median"
        ),
        alelos=(
            "allele",
            lambda x: ", ".join(sorted(x.unique()))
        )
    ))

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,AAIKDNRAV,186,194,7,2.70,"HLA-A*02:03, HLA-A*02:06, HLA-A*68:02, HLA-B*0..."
1,AAIKDNRAVH,186,195,2,4.20,"HLA-A*30:02, HLA-B*15:01"
2,ADMGYWIESAL,196,206,1,3.00,HLA-B*40:01
3,AECPNTNRA,141,149,3,1.00,"HLA-B*40:01, HLA-B*44:02, HLA-B*44:03"
4,AECPNTNRAW,141,150,8,1.70,"HLA-A*01:01, HLA-A*23:01, HLA-B*40:01, HLA-B*4..."
...,...,...,...,...,...,...
585,YSWKTWGKA,113,121,2,4.40,"HLA-A*30:02, HLA-A*68:02"
586,YSWKTWGKAK,113,122,6,2.05,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
587,YSWKTWGKAKM,113,123,2,2.40,"HLA-B*57:01, HLA-B*58:01"
588,YWIESALNDTW,200,210,9,1.10,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*4..."
589,YWIESALNDTWK,200,211,2,4.25,"HLA-A*23:01, HLA-A*24:02"

# Filtragem por epítopos presentes em mais de determinada quantidade de alelos.

In [5]:
epitopos_repetidos = epitopos_repetidos[
    epitopos_repetidos["qte_de_alelos"] >= 10
].reset_index(drop=True)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,ASGKLITEW,303,311,12,1.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
1,AVHADMGYW,193,201,10,1.645,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
2,CHWPKSHTL,223,231,12,2.600,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3..."
3,CTLPPLRYR,316,324,11,0.960,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
4,DTWKIEKASF,208,217,12,2.950,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
5,ELKYSWKTW,110,118,11,1.500,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
6,FIEVKNCHW,217,225,10,3.200,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
7,FITDNVHTW,20,28,22,1.150,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
8,FQPESPSKL,34,42,18,1.600,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
9,FTTNIWLKL,163,171,16,1.650,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
10,GIFITDNVHTW,18,28,10,0.770,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
11,HTQITGPWHL,261,270,13,1.700,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
12,HTWTEQYKF,26,34,21,1.500,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
13,HWPKSHTLW,224,232,14,2.450,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
14,IESALNDTW,202,210,10,1.150,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."
15,IFITDNVHTW,19,28,11,0.340,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
16,ILSENEVKL,78,86,13,2.800,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
17,IMQAGKRSL,96,104,11,2.200,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
18,ITGPWHLGK,264,272,11,2.600,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
19,ITPELNHIL,71,79,17,1.700,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
20,KFQPESPSKL,33,42,12,2.550,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
21,KLKEKQDVF,170,178,20,2.100,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
22,KQITPELNH,69,77,10,2.350,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
23,KQITPELNHI,69,78,11,2.900,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
24,KQITPELNHIL,69,79,10,2.250,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
25,KRSLRPQPTEL,101,111,10,2.250,"HLA-A*02:01, HLA-A*02:03, HLA-A*30:01, HLA-A*3..."
26,KTWGKAKML,116,124,18,2.400,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
27,LRPQPTELKY,104,113,14,3.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
28,LSTESHNQTF,124,133,10,2.400,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
29,MLSTESHNQTF,123,133,11,1.800,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
30,MWKQITPEL,67,75,17,2.200,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
31,NLAGPVSQH,246,254,10,3.250,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1..."
32,NTNRAWNSL,145,153,12,3.550,"HLA-A*01:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
33,NVHTWTEQY,24,32,16,1.550,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
34,QITPELNHI,70,78,12,2.850,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
35,QPTELKYSW,107,115,14,0.835,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
36,RAVHADMGY,192,200,12,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
37,RPQPTELKY,105,113,19,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
38,RPQPTELKYSW,105,115,12,1.350,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
39,RSCTLPPLR,314,322,10,1.950,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
40,RSCTLPPLRY,314,323,11,1.300,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
41,RSCTLPPLRYR,314,324,11,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
42,RSLRPQPTEL,102,111,14,1.080,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
43,RSLRPQPTELKY,102,113,12,0.820,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
44,RSVTRLENL,58,66,11,2.300,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
45,SALNDTWKI,204,212,11,1.400,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
46,SCTLPPLRY,315,323,13,2.000,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
47,SCTLPPLRYR,315,324,10,0.660,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
48,SEMIIPKNL,239,247,11,4.100,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-B*0..."
49,SENEVKLTI,80,88,18,3.000,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
50,SLRPQPTEL,103,111,21,2.500,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
51,SLRPQPTELK,103,112,11,1.900,"HLA-A*02:03, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
52,SLRPQPTELKY,103,113,16,1.350,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
53,SQHNYRPGY,252,260,14,1.285,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
54,STESHNQTF,125,133,18,1.200,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
55,SVTRLENLM,59,67,10,3.800,"HLA-A*02:06, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
56,TASGKLITEW,302,311,11,2.800,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
57,TQITGPWHL,262,270,22,1.750,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
58,VEDYGFGVF,155,163,11,3.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
59,VTRLENLMW,60,68,12,3.250,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

In [6]:
epitopos_repetidos = (
    epitopos_repetidos
    .sort_values(
        ["qte_de_alelos", "median_binding_percentile"],
        ascending=[False, True]
    )
    .reset_index(drop=True)
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,FITDNVHTW,20,28,22,1.150,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
1,TQITGPWHL,262,270,22,1.750,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
2,HTWTEQYKF,26,34,21,1.500,"HLA-A*01:01, HLA-A*02:06, HLA-A*11:01, HLA-A*2..."
3,SLRPQPTEL,103,111,21,2.500,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
4,KLKEKQDVF,170,178,20,2.100,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
5,RPQPTELKY,105,113,19,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
6,STESHNQTF,125,133,18,1.200,"HLA-A*01:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
7,FQPESPSKL,34,42,18,1.600,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
8,KTWGKAKML,116,124,18,2.400,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
9,SENEVKLTI,80,88,18,3.000,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:06, HLA-A*2..."
10,ITPELNHIL,71,79,17,1.700,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
11,MWKQITPEL,67,75,17,2.200,"HLA-A*02:03, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
12,SLRPQPTELKY,103,113,16,1.350,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
13,NVHTWTEQY,24,32,16,1.550,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
14,FTTNIWLKL,163,171,16,1.650,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
15,QPTELKYSW,107,115,14,0.835,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
16,RSLRPQPTEL,102,111,14,1.080,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*0..."
17,SQHNYRPGY,252,260,14,1.285,"HLA-A*01:01, HLA-A*02:06, HLA-A*03:01, HLA-A*1..."
18,HWPKSHTLW,224,232,14,2.450,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
19,LRPQPTELKY,104,113,14,3.100,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
20,HTQITGPWHL,261,270,13,1.700,"HLA-A*01:01, HLA-A*02:01, HLA-A*02:03, HLA-A*0..."
21,SCTLPPLRY,315,323,13,2.000,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
22,ILSENEVKL,78,86,13,2.800,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
23,RSLRPQPTELKY,102,113,12,0.820,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
24,RAVHADMGY,192,200,12,1.200,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
25,RPQPTELKYSW,105,115,12,1.350,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*0..."
26,ASGKLITEW,303,311,12,1.600,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
27,KFQPESPSKL,33,42,12,2.550,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
28,CHWPKSHTL,223,231,12,2.600,"HLA-A*23:01, HLA-A*24:02, HLA-A*30:02, HLA-A*3..."
29,QITPELNHI,70,78,12,2.850,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
30,DTWKIEKASF,208,217,12,2.950,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
31,VTRLENLMW,60,68,12,3.250,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
32,NTNRAWNSL,145,153,12,3.550,"HLA-A*01:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
33,IFITDNVHTW,19,28,11,0.340,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
34,CTLPPLRYR,316,324,11,0.960,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
35,RSCTLPPLRY,314,323,11,1.300,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
36,RSCTLPPLRYR,314,324,11,1.400,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
37,SALNDTWKI,204,212,11,1.400,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
38,ELKYSWKTW,110,118,11,1.500,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
39,MLSTESHNQTF,123,133,11,1.800,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
40,SLRPQPTELK,103,112,11,1.900,"HLA-A*02:03, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
41,IMQAGKRSL,96,104,11,2.200,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
42,RSVTRLENL,58,66,11,2.300,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
43,ITGPWHLGK,264,272,11,2.600,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*3..."
44,TASGKLITEW,302,311,11,2.800,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
45,KQITPELNHI,69,78,11,2.900,"HLA-A*02:01, HLA-A*02:03, HLA-A*02:06, HLA-A*2..."
46,VEDYGFGVF,155,163,11,3.300,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
47,SEMIIPKNL,239,247,11,4.100,"HLA-A*02:06, HLA-A*23:01, HLA-A*24:02, HLA-B*0..."
48,SCTLPPLRYR,315,324,10,0.660,"HLA-A*01:01, HLA-A*03:01, HLA-A*11:01, HLA-A*2..."
49,GIFITDNVHTW,18,28,10,0.770,"HLA-A*23:01, HLA-A*24:02, HLA-A*26:01, HLA-A*3..."
50,IESALNDTW,202,210,10,1.150,"HLA-A*23:01, HLA-A*24:02, HLA-A*32:01, HLA-B*3..."
51,AVHADMGYW,193,201,10,1.645,"HLA-A*23:01, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."
52,RSCTLPPLR,314,322,10,1.950,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
53,KQITPELNHIL,69,79,10,2.250,"HLA-A*02:01, HLA-A*02:06, HLA-A*23:01, HLA-A*2..."
54,KRSLRPQPTEL,101,111,10,2.250,"HLA-A*02:01, HLA-A*02:03, HLA-A*30:01, HLA-A*3..."
55,KQITPELNH,69,77,10,2.350,"HLA-A*03:01, HLA-A*11:01, HLA-A*30:01, HLA-A*3..."
56,LSTESHNQTF,124,133,10,2.400,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."
57,FIEVKNCHW,217,225,10,3.200,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*3..."
58,NLAGPVSQH,246,254,10,3.250,"HLA-A*01:01, HLA-A*02:03, HLA-A*03:01, HLA-A*1..."
59,SVTRLENLM,59,67,10,3.800,"HLA-A*02:06, HLA-A*26:01, HLA-A*30:02, HLA-A*3..."