# Análise de dados TCP-CII

### Importação dos parâmetros universais

In [52]:
import importlib.util
from pathlib import Path

path = Path("../../../parametros/config.py").resolve()

spec = importlib.util.spec_from_file_location("parametros", path)
parametros = importlib.util.module_from_spec(spec)
spec.loader.exec_module(parametros)

In [53]:
# Parâmetros importados do arquivo config.py
print(
    "Filtrar por quantidade de alelos TCC1:.........................",
    parametros.filtarar_por_qte_de_alelos_tcc1,
)
print(
    "Parâmetro de filtragem median binding percentile TCC1:.........",
    parametros.parametro_de_filtragem_mbp_tcc1,
)
print(
    "Percentual de match mínimo TCC1:...............................",
    parametros.percent_match_minimo_tcc1,
)

Filtrar por quantidade de alelos TCC1:......................... 10
Parâmetro de filtragem median binding percentile TCC1:......... 1
Percentual de match mínimo TCC1:............................... 95.0

In [54]:
import pandas as pd

In [55]:
df = pd.read_csv('./T CELL/DENV 2 - T Cell Prediction - Class I.csv')
df

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTRLENLMW,60,68,9,HLA-B*57:01,60,0.01,VTRLENLMW,VTRLENLMW,0.993804,0.01
1,1,ASGKLITEW,303,311,9,HLA-B*57:01,303,0.01,ASGKLITEW,ASGKLITEW,0.990493,0.01
2,1,ASGKLITEW,303,311,9,HLA-B*58:01,303,0.01,ASGKLITEW,ASGKLITEW,0.989009,0.01
3,1,ETAECPNTNR,139,148,10,HLA-A*68:01,483,0.01,ETAEPNTNR,ETAECPNTNR,0.981131,0.01
4,1,QPTELKYSW,107,115,9,HLA-B*53:01,107,0.01,QPTELKYSW,QPTELKYSW,0.980907,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
36985,1,LKEKEENLVNS,338,348,11,HLA-A*32:01,1025,100.00,KEKENLVNS,KEKEENLVNS,0.000000,100.00
36986,1,LKEKEENLVNS,338,348,11,HLA-B*53:01,1025,100.00,LKEENLVNS,LKEKEENLVNS,0.000000,100.00
36987,1,EKEENLVNSLVT,340,351,12,HLA-A*11:01,1369,100.00,ENLVNSLVT,EKEENLVNSLVT,0.000000,100.00
36988,1,EKEENLVNSLVT,340,351,12,HLA-A*32:01,1369,100.00,EEENLVNSL,EKEENLVNSL,0.000000,100.00
36989,1,EKEENLVNSLVT,340,351,12,HLA-A*68:01,1369,100.00,EKEENLVNT,EKEENLVNSLVT,0.000000,100.00

## Selecionando Epítopos por median binding percentile.

In [56]:
mbp_minimo = parametros.parametro_de_filtragem_mbp_tcc1

In [57]:
df_mbp_m5 = df[df['median binding percentile'] < mbp_minimo].copy()
print("Filtrando por median binding percentile < ", mbp_minimo)
df_mbp_m5

Filtrando por median binding percentile <  1

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,VTRLENLMW,60,68,9,HLA-B*57:01,60,0.01,VTRLENLMW,VTRLENLMW,0.993804,0.01
1,1,ASGKLITEW,303,311,9,HLA-B*57:01,303,0.01,ASGKLITEW,ASGKLITEW,0.990493,0.01
2,1,ASGKLITEW,303,311,9,HLA-B*58:01,303,0.01,ASGKLITEW,ASGKLITEW,0.989009,0.01
3,1,ETAECPNTNR,139,148,10,HLA-A*68:01,483,0.01,ETAEPNTNR,ETAECPNTNR,0.981131,0.01
4,1,QPTELKYSW,107,115,9,HLA-B*53:01,107,0.01,QPTELKYSW,QPTELKYSW,0.980907,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
577,1,NCHWPKSHTLW,222,232,11,HLA-B*57:01,909,0.99,NCHKSHTLW,NCHWPKSHTLW,0.276588,0.99
578,1,NIWLKLKEK,166,174,9,HLA-A*03:01,166,0.99,NIWLKLKEK,NIWLKLKEK,0.184003,0.99
579,1,KLTIMTGDIK,85,94,10,HLA-A*11:01,429,0.99,KTIMTGDIK,KLTIMTGDIK,0.169069,0.99
580,1,RAVHADMGYWI,192,202,11,HLA-B*58:01,879,0.99,RAVHADMYW,RAVHADMGYW,0.146511,0.99
581,1,TELKYSWKT,109,117,9,HLA-B*44:03,109,0.99,TELKYSWKT,TELKYSWKT,0.073295,0.99

## Agrupando por pepitideos e agregando colunas pertinentes

In [58]:
epitopos_repetidos = (
    df_mbp_m5
    .groupby('peptide', as_index=False)
    .agg(
        start=("start", "first"),
        end=("end", "first"),
        qte_de_alelos=("allele", "nunique"),
        median_binding_percentile=(
            "median binding percentile",
            "median"
        ),
        alelos=(
            "allele",
            lambda x: ", ".join(sorted(x.unique()))
        )
    )
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,AECPNTNRA,141,149,1,0.940,HLA-B*44:03
1,AECPNTNRAW,141,150,2,0.010,"HLA-B*44:02, HLA-B*44:03"
2,AECPNTNRAWN,141,151,2,0.465,"HLA-B*44:02, HLA-B*44:03"
3,AGPVSQHNY,248,256,1,0.490,HLA-A*30:02
4,ALNDTWKIEK,205,214,2,0.180,"HLA-A*03:01, HLA-A*11:01"
...,...,...,...,...,...,...
223,WIESALNDTW,201,210,2,0.390,"HLA-B*44:02, HLA-B*44:03"
224,YGFGVFTTNIW,158,168,3,0.380,"HLA-B*53:01, HLA-B*57:01, HLA-B*58:01"
225,YGMEIRPLK,331,339,2,0.465,"HLA-A*11:01, HLA-A*30:01"
226,YHTQITGPWHL,260,270,2,0.485,"HLA-A*02:01, HLA-A*02:06"
227,YWIESALNDTW,200,210,4,0.270,"HLA-A*23:01, HLA-A*24:02, HLA-B*44:02, HLA-B*4..."

## Filtragem por qte_de_alelos

In [59]:
# mbp_minimo = 1
qte_alelos_minimo = parametros.filtarar_por_qte_de_alelos_tcc1

In [60]:
# Filtro do número de alelos
epitopos_repetidos = epitopos_repetidos[
    epitopos_repetidos["qte_de_alelos"] >= qte_alelos_minimo
].reset_index(drop=True)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,HTWTEQYKF,26,34,10,0.28,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

## Sorting por median_biding_percentile

In [61]:
epitopos_repetidos = (
    epitopos_repetidos
    .sort_values(
        ["median_binding_percentile", "qte_de_alelos"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

epitopos_repetidos

,peptide,start,end,qte_de_alelos,median_binding_percentile,alelos
0,HTWTEQYKF,26,34,10,0.28,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

## Separando epítopos e criando arquivo FASTA para IEDB analysis resource

In [62]:
pepitides = epitopos_repetidos.peptide

with open("./peptideos_tcell_1.fasta", "w") as f:
    for i, peptide in enumerate(pepitides, start=1):
        f.write(f">NP {i}\n")
        f.write(f"{peptide}\n")
        
pepitides

0    HTWTEQYKF
Name: peptide, dtype: str

### Seqkit remove sequências proteicas contendo gaps e *.

In [63]:
# !seqkit grep -s -v -r -p '[-*]' './Fastas/denv1_NS1_proteinas.fa' > DENV1_seq_filter_all.fasta

### Resultado IEDB analysis resource

In [64]:
conservacy_result = pd.read_csv('./ConservancyResult_tcell_1.csv')
conservacy_result

,Epitope #,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,View details
0,1,NP 1,HTWTEQYKF,9,99.77% (864/866),88.89%,100.00%,NaN

### Merge da coluna qte_de_alelos ao dataframe conservacy_result

In [65]:
# qte_de_alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "qte_de_alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("View details"))

# qte_de_alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "median_binding_percentile"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide"))

# alelos
conservacy_result = conservacy_result.merge(
    epitopos_repetidos[["peptide", "alelos"]],
    left_on="Epitope sequence",
    right_on="peptide",
    how="left"
).drop(columns=("peptide")).drop(columns=("Epitope #"))

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,median_binding_percentile,alelos
0,NP 1,HTWTEQYKF,9,99.77% (864/866),88.89%,100.00%,10,0.28,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2..."

### Gerando a coluna percent_match para filtrar os epitopos com percentagem de match maior que 50%

In [66]:
col = "Percent of protein sequence matches at identity <= 100%"

conservacy_result["percent_match"] = (
    conservacy_result[col]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
    .astype(float)
)

conservacy_result

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,median_binding_percentile,alelos,percent_match
0,NP 1,HTWTEQYKF,9,99.77% (864/866),88.89%,100.00%,10,0.28,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.77

### Sort e filtragem por percent_match e presença em alelos

In [67]:
minimum_percent_match = parametros.percent_match_minimo_tcc1

In [68]:
# Filtro do Percent match
conservacy_result_filtered = (
    conservacy_result[conservacy_result["percent_match"] >= minimum_percent_match]
    .sort_values(
            by="percent_match", 
            ascending=False
        )
    ).reset_index(drop=True)

conservacy_result_filtered

,Epitope name,Epitope sequence,Epitope length,Percent of protein sequence matches at identity <= 100%,Minimum identity,Maximum identity,qte_de_alelos,median_binding_percentile,alelos,percent_match
0,NP 1,HTWTEQYKF,9,99.77% (864/866),88.89%,100.00%,10,0.28,"HLA-A*01:01, HLA-A*23:01, HLA-A*24:02, HLA-A*2...",99.77